import { spawn } from "node:child_process";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { deferred } from "./helpers/async.js";
import { createLifecycleLocations } from "../src/plugin-lifecycle/locations.js";
import { acquireLifecycleLocks, heartbeatLifecycleLocks, lifecycleLockDirectory, releaseLifecycleLocks, validateLifecycleLockLease, type LifecycleLockLease } from "../src/plugin-lifecycle/locks.js";
import { previewRecovery, recoverTransaction } from "../src/plugin-lifecycle/recovery.js";
import { canonicalJsonBytes, establishOwnedStateStore, ownedRecordPartition, sha256, type OwnedStateStore, type StoreResult } from "../src/plugin-lifecycle/state-store.js";
import {
  createTransactionCodecRegistry, executeTransaction, prepareTransaction, readTransactionJournal, readTransactionReceipt,
  type TransactionFaultPhase, type TransactionParticipant, type TransactionProducerCodec,
} from "../src/plugin-lifecycle/transaction.js";

const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => fs.rm(root, { recursive: true, force: true }))); });
function requiredLocks(_summary: unknown, participants: readonly TransactionParticipant[]) {
  const first = participants[0]; if (first === undefined) return { ok: false as const, code: "locks", message: "missing participant" };
  const profileKey = path.basename(path.dirname(path.dirname(first.stagedPath)));
  return { ok: true as const, value: [{ kind: "profile" as const, key: profileKey }, { kind: "checkout" as const, key: "checkout-main" }, { kind: "settings" as const, key: "settings-user" }] };
}
const codec: TransactionProducerCodec<{ readonly label: string }> = { schema: "test.transaction", version: 1,
  decodeSummary(value): StoreResult<{ readonly label: string }> { return typeof value === "object" && value !== null && Object.keys(value).length === 1 && typeof (value as { label?: unknown }).label === "string" ? { ok: true, value: value as { label: string } } : { ok: false, code: "summary", message: "invalid" }; },
  validatePlan: () => ({ ok: true, value: undefined }), requiredLocks,
};
function registry(selected: TransactionProducerCodec = codec) { const result = createTransactionCodecRegistry([selected]); if (!result.ok) throw new Error(result.message); return result.value; }
async function fixture(profile = "profile", existingHome?: string): Promise<OwnedStateStore> { const home = existingHome ?? await fs.mkdtemp(path.join(os.tmpdir(), "picc-tx-")); if (existingHome === undefined) { roots.push(home); if (process.platform !== "win32") await fs.chmod(home, 0o700); } const locations = createLifecycleLocations({ homeDir: home, profilePath: path.join(home, profile), platform: process.platform === "win32" ? "win32" : "posix" }); if (!locations.ok) throw new Error(locations.error.message); const result = await establishOwnedStateStore(locations.value, home); if (!result.ok) throw new Error(result.message); return result.value; }
async function stage(store: OwnedStateStore, name: string, text: string) { const candidate = path.join(store.stagingRoot, name); const bytes = Buffer.from(text); await fs.writeFile(candidate, bytes, { mode: 0o600, flag: "wx" }); return { path: candidate, digest: sha256(bytes) }; }
async function participant(store: OwnedStateStore, key: string, text: string, generationId?: string): Promise<TransactionParticipant> {
  const staged = await stage(store, `${key}.stage`, text); const partition = ownedRecordPartition(store, "producer", "user"); if (!partition.ok) throw new Error(partition.message); await fs.mkdir(partition.value, { recursive: true, mode: 0o700 });
  return { kind: generationId === undefined ? "test.record" : "test.generation", key, ownerKey: "producer", scopeKey: "user", targetPath: path.join(generationId === undefined ? partition.value : store.generationsRoot, `${key}.json`), targetClass: generationId === undefined ? "owned" : "generation", precondition: { state: "absent" }, stagedPath: staged.path, stagedDigest: staged.digest, rollback: { kind: "delete-new-target" }, producerEvidence: { key }, ...(generationId === undefined ? {} : { generationId }) };
}
function lockVector(store: OwnedStateStore) { return [{ kind: "profile" as const, key: store.profileKey }, { kind: "checkout" as const, key: "checkout-main" }, { kind: "settings" as const, key: "settings-user" }]; }
async function lease(store: OwnedStateStore, operationId: string, recovery = false): Promise<LifecycleLockLease> { const result = await acquireLifecycleLocks({ store, operationId, identities: lockVector(store), ...(recovery ? { expectedRecoveryOperationId: operationId, processProbe: { observe: async () => ({ state: "absent" as const }) } } : {}) }); if (!result.ok) throw new Error(`${result.code}: ${result.message}`); return result.value; }
async function prepared(store: OwnedStateStore, operationId: string, participants: readonly TransactionParticipant[], selected: TransactionProducerCodec = codec) { const result = await prepareTransaction({ store, codec: selected, operationId, confirmationSummary: { label: operationId }, participants }); if (!result.ok) throw new Error(`${result.code}: ${result.message}`); return result.value; }
async function exists(candidate: string): Promise<boolean> { return fs.lstat(candidate).then(() => true, () => false); }
async function bytes(candidate: string): Promise<string | undefined> { return fs.readFile(candidate, "utf8").catch((error: NodeJS.ErrnoException) => error.code === "ENOENT" ? undefined : Promise.reject(error)); }
async function recovery(store: OwnedStateStore, operationId: string, action: "complete" | "rollback", selected: TransactionProducerCodec, held: LifecycleLockLease, faults?: { hit: (phase: TransactionFaultPhase, index?: number) => void | Promise<void> }) {
  const preview = await previewRecovery({ store, operationId, registry: registry(selected) }); if (!preview.ok) throw new Error(`${preview.code}: ${preview.message}`);
  return recoverTransaction({ store, operationId, action, confirmedProducerSchema: selected.schema, confirmedProducerVersion: selected.version, confirmedPlanDigest: preview.value.planDigest, confirmedConfirmationDigest: preview.value.confirmationDigest, registry: registry(selected), lease: held, ...(faults === undefined ? {} : { faults }) });
}

describe("owned lifecycle transactions", () => {
  it("executes the same operation id independently in two profiles under one home", async () => {
    const base = await fs.mkdtemp(path.join(os.tmpdir(), "picc-two-profiles-")); roots.push(base); if (process.platform !== "win32") await fs.chmod(base, 0o700); const first = await fixture("one", base); const second = await fixture("two", base);
    for (const [store, text] of [[first, "first"], [second, "second"]] as const) { const plan = await prepared(store, "same-operation", [await participant(store, "record", text)]); const held = await lease(store, "same-operation"); expect(await executeTransaction(store, plan, { lease: held })).toMatchObject({ state: "committed" }); await releaseLifecycleLocks(held); }
    expect(await fs.readFile(path.join((ownedRecordPartition(first, "producer", "user") as { ok: true; value: string }).value, "record.json"), "utf8")).toBe("first"); expect(await fs.readFile(path.join((ownedRecordPartition(second, "producer", "user") as { ok: true; value: string }).value, "record.json"), "utf8")).toBe("second");
  });

  it("binds the exact ordered profile, checkout, and settings lease into the immutable plan", async () => {
    const store = await fixture(); const summary = { label: "exact-locks" }; const evidence = { key: "record" }; const raw = await participant(store, "exact-locks", "payload"); const mutable = { ...raw, producerEvidence: evidence }; const mutableCodec = { ...codec };
    const made = await prepareTransaction({ store, codec: mutableCodec, operationId: "exact-locks", confirmationSummary: summary, participants: [mutable] }); if (!made.ok) throw new Error(made.message); const plan = made.value;
    expect(plan.requiredLocks).toEqual(lockVector(store)); expect(Object.isFrozen(plan.confirmationSummary)).toBe(true); expect(Object.isFrozen(plan.participants[0]!.producerEvidence)).toBe(true);
    summary.label = "mutated"; evidence.key = "mutated"; mutable.key = "mutated"; mutableCodec.validatePlan = () => ({ ok: false, code: "replaced", message: "replaced" });
    const variants = [lockVector(store).slice(0, 2), [...lockVector(store), { kind: "settings" as const, key: "settings-z" }], [lockVector(store)[0]!, lockVector(store)[2]!, lockVector(store)[1]!], [lockVector(store)[0]!, lockVector(store)[1]!, { kind: "settings" as const, key: "wrong" }]];
    for (const [index, identities] of variants.entries()) {
      const acquired = await acquireLifecycleLocks({ store, operationId: "exact-locks", identities });
      if (index === 2) expect(acquired).toMatchObject({ ok: false, code: "invalid-lock-order" });
      else if (acquired.ok) { expect(await executeTransaction(store, plan, { lease: acquired.value })).toMatchObject({ state: "rejected" }); await releaseLifecycleLocks(acquired.value); }
      else throw new Error(acquired.message);
    }
    const held = await acquireLifecycleLocks({ store, operationId: "exact-locks", identities: lockVector(store) }); if (!held.ok) throw new Error(held.message);
    expect(await executeTransaction(store, plan, { lease: held.value })).toMatchObject({ state: "committed", receipt: { confirmationSummary: { label: "exact-locks" }, participants: [{ key: "exact-locks", producerEvidence: { key: "record" } }] } }); await releaseLifecycleLocks(held.value);
  });

  it("requires a live store/operation/profile lease and independently enforces unique generation-last", async () => {
    const store = await fixture(); const ordinary = await participant(store, "record", "record"); const generation = await participant(store, "current", "generation", "gen-1");
    expect(await prepareTransaction({ store, codec, operationId: "bad-order", confirmationSummary: { label: "bad" }, participants: [generation, ordinary] })).toMatchObject({ ok: false, code: "invalid-plan" });
    const plan = await prepared(store, "commit", [ordinary, generation]); const otherProducer = await prepared(store, "commit", [ordinary, generation], { ...codec, schema: "test.other-producer" }); expect(await executeTransaction(store, plan)).toMatchObject({ state: "rejected" });
    const held = await lease(store, "commit"); const result = await executeTransaction(store, plan, { lease: held }); expect(result).toMatchObject({ state: "committed", receipt: { completed: 2, generationId: "gen-1" } });
    expect(await executeTransaction(store, plan, { lease: held })).toEqual(result); expect(await executeTransaction(store, otherProducer, { lease: held })).toMatchObject({ state: "rejected", cause: "Operation id is bound to a different producer or receipt" }); expect(await releaseLifecycleLocks(held)).toMatchObject({ ok: true });
    const receipt = await readTransactionReceipt(store, "commit"); expect(receipt).toMatchObject({ ok: true, value: { outcome: "committed", generationId: "gen-1" } });
  });

  it("refuses a same-id pending journal byte-identically and completes only through explicit plan-bound recovery", async () => {
    const store = await fixture(); const parts = [await participant(store, "first", "one"), await participant(store, "second", "two")]; const plan = await prepared(store, "pending", parts); const held = await lease(store, "pending");
    expect(await executeTransaction(store, plan, { lease: held, faults: { hit(phase, index) { if (phase === "before-temp-write" && index === 1) throw new Error("fault"); } } })).toMatchObject({ state: "pending-recovery", completed: 1 });
    const journalPath = path.join(store.journalsRoot, "pending.json"); const before = await fs.readFile(journalPath); expect(await executeTransaction(store, plan, { lease: held })).toMatchObject({ state: "pending-recovery", completed: 1 }); expect(await fs.readFile(journalPath)).toEqual(before);
    const projectingCodec: TransactionProducerCodec = { ...codec, decodeSummary(value) { const decoded = codec.decodeSummary(value); return decoded.ok ? { ok: true, value: { display: decoded.value.label.toUpperCase() } } : decoded; } }; const projectingRegistry = registry(projectingCodec);
    const preview = await previewRecovery({ store, operationId: "pending", registry: projectingRegistry }); expect(preview).toMatchObject({ ok: true, value: { confirmationSummary: { display: "PENDING" }, completed: 1, rolledBack: 0, remaining: 1, actions: ["complete", "rollback"] } }); if (!preview.ok) return;
    expect(await recoverTransaction({ store, operationId: "pending", action: "complete", confirmedProducerSchema: "test.transaction", confirmedProducerVersion: 1, confirmedPlanDigest: "sha256:wrong", confirmedConfirmationDigest: preview.value.confirmationDigest, registry: projectingRegistry, lease: held })).toMatchObject({ ok: false, code: "confirmation-mismatch" });
    expect(await recoverTransaction({ store, operationId: "pending", action: "complete", confirmedProducerSchema: "test.transaction", confirmedProducerVersion: 1, confirmedPlanDigest: preview.value.planDigest, confirmedConfirmationDigest: preview.value.confirmationDigest, registry: projectingRegistry, lease: held })).toMatchObject({ ok: true, value: { outcome: "committed" } });
    expect(await previewRecovery({ store, operationId: "pending", registry: projectingRegistry })).toMatchObject({ ok: true, value: { confirmationSummary: { display: "PENDING" }, terminalOutcome: "committed" } });
    expect(await recoverTransaction({ store, operationId: "pending", action: "complete", confirmedProducerSchema: "test.wrong", confirmedProducerVersion: 1, confirmedPlanDigest: preview.value.planDigest, confirmedConfirmationDigest: preview.value.confirmationDigest, registry: projectingRegistry, lease: held })).toMatchObject({ ok: false, code: "confirmation-mismatch" }); await releaseLifecycleLocks(held);
  });

  it("revalidates lease ownership after an awaited fault immediately before target publication", async () => {
    const store = await fixture(); const p = await participant(store, "lost-after-fault", "never-published"); const plan = await prepared(store, "lost-after-fault", [p]); const held = await lease(store, "lost-after-fault"); let released = false;
    const result = await executeTransaction(store, plan, { lease: held, faults: { async hit(phase) { if (!released && phase === "before-replacement") { released = true; expect(await releaseLifecycleLocks(held)).toMatchObject({ ok: true }); } } } });
    expect(result).toMatchObject({ state: "pending-recovery", completed: 0 }); await expect(fs.stat(p.targetPath)).rejects.toMatchObject({ code: "ENOENT" }); expect(await readTransactionReceipt(store, "lost-after-fault")).toEqual({ ok: true, value: undefined }); expect(await readTransactionJournal(store, "lost-after-fault")).toMatchObject({ ok: true, value: { completed: 0 } });
  });

  it("refuses target substitution at the final execute, completion, restore, and delete boundaries", async () => {
    const executeStore = await fixture(); const executePart = await participant(executeStore, "boundary-execute", "new"); const executePlan = await prepared(executeStore, "boundary-execute", [executePart]); const executeLease = await lease(executeStore, "boundary-execute");
    expect(await executeTransaction(executeStore, executePlan, { lease: executeLease, faults: { async hit(phase) { if (phase === "before-replacement") await fs.writeFile(executePart.targetPath, "intruder"); } } })).toMatchObject({ state: "failed-before-commit", receipt: { failureCategory: "stale-precondition" } }); expect(await bytes(executePart.targetPath)).toBe("intruder"); await releaseLifecycleLocks(executeLease);

    const completionStore = await fixture(); const completionParts = [await participant(completionStore, "boundary-complete-first", "one"), await participant(completionStore, "boundary-complete-second", "two")]; const completionPlan = await prepared(completionStore, "boundary-complete", completionParts); const completionLease = await lease(completionStore, "boundary-complete");
    expect(await executeTransaction(completionStore, completionPlan, { lease: completionLease, faults: { hit(phase, index) { if (phase === "before-temp-write" && index === 1) throw new Error("pending"); } } })).toMatchObject({ state: "pending-recovery", completed: 1 });
    expect(await recovery(completionStore, "boundary-complete", "complete", codec, completionLease, { async hit(phase, index) { if (phase === "before-replacement" && index === 1) await fs.writeFile(completionParts[1]!.targetPath, "intruder"); } })).toMatchObject({ ok: false, code: "recovery-interrupted" }); expect(await bytes(completionParts[1]!.targetPath)).toBe("intruder"); await releaseLifecycleLocks(completionLease);

    for (const rollbackKind of ["restore", "delete"] as const) { const store = await fixture(); let p = await participant(store, `boundary-${rollbackKind}`, "new"); if (rollbackKind === "restore") { await fs.writeFile(p.targetPath, "old"); const backup = await stage(store, "boundary-restore.backup", "old"); p = { ...p, precondition: { state: "present", digest: sha256(Buffer.from("old")) }, rollback: { kind: "restore-backup", path: backup.path, digest: backup.digest } }; } const plan = await prepared(store, `boundary-${rollbackKind}`, [p]); const held = await lease(store, `boundary-${rollbackKind}`);
      expect(await executeTransaction(store, plan, { lease: held, faults: { hit(phase) { if (phase === "after-replacement") throw new Error("pending"); } } })).toMatchObject({ state: "pending-recovery", completed: 1 });
      expect(await recovery(store, `boundary-${rollbackKind}`, "rollback", codec, held, { async hit(phase) { if (phase === "before-replacement") await fs.writeFile(p.targetPath, "intruder"); } })).toMatchObject({ ok: false, code: "recovery-interrupted" }); expect(await bytes(p.targetPath)).toBe("intruder"); await releaseLifecycleLocks(held); }
  });

  it("uses exact bounded precommit categories and does not leak secret canaries", async () => {
    const cases = [
      { id: "cancelled", setup: async (_p: TransactionParticipant) => undefined, signal: true, category: "cancelled" },
      { id: "stale", setup: async (p: TransactionParticipant) => fs.writeFile(p.targetPath, "changed"), signal: false, category: "stale-precondition" },
      { id: "staged", setup: async (p: TransactionParticipant) => fs.writeFile(p.stagedPath, "changed"), signal: false, category: "changed-staged" },
    ] as const;
    for (const item of cases) { const store = await fixture(); const p = await participant(store, item.id, "SECRET_CANARY_PAYLOAD"); const plan = await prepared(store, item.id, [p]); await item.setup(p); const held = await lease(store, item.id); const controller = new AbortController(); if (item.signal) controller.abort(); const result = await executeTransaction(store, plan, { lease: held, signal: controller.signal }); expect(result, item.id).toMatchObject({ state: "failed-before-commit", receipt: { failureCategory: item.category, completed: 0 } }); const freshPreview = await previewRecovery({ store, operationId: item.id, registry: registry() }); expect(freshPreview, item.id).toMatchObject({ ok: true, value: { terminalOutcome: "failed-before-commit", failureCategory: item.category } }); if (freshPreview.ok) expect(freshPreview.value, item.id).not.toHaveProperty("generationId"); expect(JSON.stringify(result)).not.toContain("SECRET_CANARY_PAYLOAD"); await releaseLifecycleLocks(held); }
  });

  it("cancels exactly before each participant and after each committed prefix without early generation publication", async () => {
    const table = [
      { name: "before-0", abortAt: "initial", expected: "failed-before-commit", completed: 0 },
      { name: "before-1", abortAt: "journal-0", expected: "pending-recovery", completed: 1 },
      { name: "before-2", abortAt: "journal-1", expected: "pending-recovery", completed: 2 },
      { name: "after-prefix-1", abortAt: "replacement-0", expected: "pending-recovery", completed: 1 },
      { name: "after-prefix-2", abortAt: "replacement-1", expected: "pending-recovery", completed: 2 },
      { name: "after-prefix-3", abortAt: "replacement-2", expected: "committed", completed: 3 },
    ] as const;
    for (const row of table) { const store = await fixture(); const parts = [await participant(store, `${row.name}-a`, "one"), await participant(store, `${row.name}-b`, "two"), await participant(store, `${row.name}-generation`, "generation", `cancel-${row.name}`)]; const plan = await prepared(store, row.name, parts); const held = await lease(store, row.name); const controller = new AbortController(); if (row.abortAt === "initial") controller.abort();
      const result = await executeTransaction(store, plan, { lease: held, signal: controller.signal, faults: { hit(phase, index) { if ((row.abortAt === `journal-${index}` && phase === "after-journal") || (row.abortAt === `replacement-${index}` && phase === "after-replacement")) controller.abort(); } } }); expect(result.state, row.name).toBe(row.expected); expect("completed" in result ? result.completed : "receipt" in result ? result.receipt.completed : -1, row.name).toBe(row.completed);
      expect(await Promise.all(parts.map((item) => bytes(item.targetPath))), row.name).toEqual(row.completed === 0 ? [undefined, undefined, undefined] : row.completed === 1 ? ["one", undefined, undefined] : row.completed === 2 ? ["one", "two", undefined] : ["one", "two", "generation"]);
      expect(await exists(parts[2]!.targetPath), `${row.name}.generation`).toBe(row.completed === 3); const receipt = await readTransactionReceipt(store, row.name); expect(receipt.ok ? receipt.value?.outcome : "invalid", row.name).toBe(row.expected === "failed-before-commit" ? "failed-before-commit" : row.expected === "committed" ? "committed" : undefined); if (row.expected === "failed-before-commit" && receipt.ok) expect(receipt.value?.failureCategory).toBe("cancelled"); await releaseLifecycleLocks(held); }
  });

  it("proves every execution fault phase against a three-participant byte, prefix, receipt, preview, and recovery table", async () => {
    const table: readonly { phase: TransactionFaultPhase; faultIndex?: number; state: "failed-before-commit" | "pending-recovery" | "committed"; completed: number; receipt: "failed" | "none" | "committed"; journal: boolean; bytes: readonly (string | undefined)[]; actions: readonly ("complete" | "rollback")[] }[] = [
      { phase: "before-journal", state: "failed-before-commit", completed: 0, receipt: "failed", journal: false, bytes: [undefined, undefined, undefined], actions: [] },
      { phase: "after-journal", state: "failed-before-commit", completed: 0, receipt: "failed", journal: false, bytes: [undefined, undefined, undefined], actions: [] },
      { phase: "before-temp-write", faultIndex: 1, state: "pending-recovery", completed: 1, receipt: "none", journal: true, bytes: ["one", undefined, undefined], actions: ["complete", "rollback"] },
      { phase: "after-temp-write", faultIndex: 1, state: "pending-recovery", completed: 1, receipt: "none", journal: true, bytes: ["one", undefined, undefined], actions: ["complete", "rollback"] },
      { phase: "after-flush", faultIndex: 1, state: "pending-recovery", completed: 1, receipt: "none", journal: true, bytes: ["one", undefined, undefined], actions: ["complete", "rollback"] },
      { phase: "before-replacement", faultIndex: 1, state: "pending-recovery", completed: 1, receipt: "none", journal: true, bytes: ["one", undefined, undefined], actions: ["complete", "rollback"] },
      { phase: "after-replacement", faultIndex: 1, state: "pending-recovery", completed: 2, receipt: "none", journal: true, bytes: ["one", "two", undefined], actions: ["complete", "rollback"] },
      { phase: "before-generation-marker", faultIndex: 2, state: "pending-recovery", completed: 2, receipt: "none", journal: true, bytes: ["one", "two", undefined], actions: ["complete", "rollback"] },
      { phase: "after-generation-marker", faultIndex: 2, state: "pending-recovery", completed: 3, receipt: "none", journal: true, bytes: ["one", "two", "generation"], actions: ["complete", "rollback"] },
      { phase: "before-receipt", state: "pending-recovery", completed: 3, receipt: "none", journal: true, bytes: ["one", "two", "generation"], actions: ["complete", "rollback"] },
      { phase: "after-receipt", state: "committed", completed: 3, receipt: "committed", journal: false, bytes: ["one", "two", "generation"], actions: [] },
      { phase: "before-retirement", state: "committed", completed: 3, receipt: "committed", journal: true, bytes: ["one", "two", "generation"], actions: [] },
      { phase: "after-retirement", state: "committed", completed: 3, receipt: "committed", journal: false, bytes: ["one", "two", "generation"], actions: [] },
    ];
    async function run(row: typeof table[number], suffix: string) { const store = await fixture(); const operationId = `execute-${table.indexOf(row)}-${suffix}`; const parts = [await participant(store, `${operationId}-a`, "one"), await participant(store, `${operationId}-b`, "two"), await participant(store, `${operationId}-generation`, "generation", `gen-${suffix}`)]; const plan = await prepared(store, operationId, parts); const held = await lease(store, operationId); let fired = false;
      const result = await executeTransaction(store, plan, { lease: held, faults: { hit(phase, index) { if (!fired && phase === row.phase && (row.faultIndex === undefined || index === row.faultIndex)) { fired = true; throw new Error("fault"); } } } }); expect(fired, row.phase).toBe(true); expect(result.state, row.phase).toBe(row.state); expect("completed" in result ? result.completed : "receipt" in result ? result.receipt.completed : -1, row.phase).toBe(row.completed); if (result.state === "failed-before-commit") expect(result.receipt.failureCategory, row.phase).toBe("storage-failure"); if (result.state === "pending-recovery") expect(result.cause, row.phase).toBe("Transaction interrupted after a committed safe prefix");
      expect(await Promise.all(parts.map((item) => bytes(item.targetPath))), row.phase).toEqual(row.bytes); const journalResult = await readTransactionJournal(store, operationId); expect(journalResult.ok, `${row.phase}.journal`).toBe(row.journal); if (journalResult.ok) { expect(journalResult.value.completed, row.phase).toBe(row.completed); expect(journalResult.value.rolledBack, row.phase).toBe(0); expect(journalResult.value.state, row.phase).toBe("pending"); }
      const receiptResult = await readTransactionReceipt(store, operationId); expect(receiptResult.ok, row.phase).toBe(true); expect(receiptResult.ok ? receiptResult.value?.outcome : undefined, row.phase).toBe(row.receipt === "none" ? undefined : row.receipt === "failed" ? "failed-before-commit" : "committed");
      const preview = await previewRecovery({ store, operationId, registry: registry() }); expect(preview.ok, row.phase).toBe(true); if (preview.ok) { expect(preview.value.actions, row.phase).toEqual(row.actions); expect(preview.value.completed, row.phase).toBe(row.completed); expect(preview.value.generationId, row.phase).toBe(row.completed === 3 ? `gen-${suffix}` : undefined); }
      for (const directory of new Set(parts.map((item) => path.dirname(item.targetPath)))) expect((await fs.readdir(directory)).filter((name) => name.includes(".tmp-")).length, `${row.phase}.temps`).toBe(0); return { store, operationId, parts, held, result }; }
    for (const row of table) {
      const complete = await run(row, "complete"); if (row.state === "pending-recovery") { expect(await recovery(complete.store, complete.operationId, "complete", codec, complete.held), row.phase).toMatchObject({ ok: true, value: { outcome: "committed", completed: 3 } }); expect(await Promise.all(complete.parts.map((item) => bytes(item.targetPath)))).toEqual(["one", "two", "generation"]); } await releaseLifecycleLocks(complete.held);
      if (row.state === "pending-recovery" && row.completed > 0) { const rollback = await run(row, "rollback"); expect(await recovery(rollback.store, rollback.operationId, "rollback", codec, rollback.held), row.phase).toMatchObject({ ok: true, value: { outcome: "rolled-back", completed: 0 } }); expect(await Promise.all(rollback.parts.map((item) => bytes(item.targetPath)))).toEqual([undefined, undefined, undefined]); await releaseLifecycleLocks(rollback.held); }
    }
  });

  it("proves complete rollback fault progress and successful rollback-only continuation at every relevant phase", async () => {
    const phases: readonly TransactionFaultPhase[] = ["before-journal", "after-journal", "before-temp-write", "after-temp-write", "after-flush", "before-replacement", "after-replacement", "before-generation-marker", "after-generation-marker", "before-receipt", "after-receipt", "before-retirement", "after-retirement"];
    for (const [caseIndex, selectedPhase] of phases.entries()) { const store = await fixture(); const operationId = `rollback-phase-${caseIndex}`; const raw = [await participant(store, `${operationId}-record`, "new-record"), await participant(store, `${operationId}-generation`, "new-generation", `rollback-gen-${caseIndex}`)]; const old = ["old-record", "old-generation"]; const parts: TransactionParticipant[] = [];
      for (const [index, item] of raw.entries()) { await fs.writeFile(item.targetPath, old[index]!); const backup = await stage(store, `${operationId}-backup-${index}`, old[index]!); parts.push({ ...item, precondition: { state: "present", digest: sha256(Buffer.from(old[index]!)) }, rollback: { kind: "restore-backup", path: backup.path, digest: backup.digest } }); }
      const plan = await prepared(store, operationId, parts); const held = await lease(store, operationId); expect(await executeTransaction(store, plan, { lease: held, faults: { hit(phase, index) { if (phase === "after-replacement" && index === 1) throw new Error("pending"); } } })).toMatchObject({ state: "pending-recovery", completed: 2 }); let fired = false;
      const interrupted = await recovery(store, operationId, "rollback", codec, held, { hit(phase, index) { const indexMatches = !["before-temp-write", "after-temp-write", "after-flush", "before-replacement", "after-replacement", "before-generation-marker", "after-generation-marker"].includes(selectedPhase) || index === 1; if (!fired && phase === selectedPhase && indexMatches) { fired = true; throw new Error("rollback-fault"); } } }); expect(fired, selectedPhase).toBe(true);
      const terminal = ["after-receipt", "before-retirement", "after-retirement"].includes(selectedPhase); expect(interrupted, selectedPhase).toMatchObject(terminal ? { ok: true, value: { outcome: "rolled-back" } } : { ok: false, code: "recovery-interrupted" });
      const preview = await previewRecovery({ store, operationId, registry: registry() }); expect(preview.ok, selectedPhase).toBe(true); if (!preview.ok) continue; expect(preview.value.actions, selectedPhase).toEqual(terminal ? [] : ["rollback"]);
      const expectedRolledBack = ["after-replacement", "after-generation-marker", "before-journal", "after-journal"].includes(selectedPhase) ? 1 : ["before-receipt", "after-receipt", "before-retirement", "after-retirement"].includes(selectedPhase) ? 2 : 0;
      expect(preview.value.rolledBack, selectedPhase).toBe(terminal ? 2 : expectedRolledBack); expect(preview.value.generationId, selectedPhase).toBe(!terminal && expectedRolledBack === 0 ? `rollback-gen-${caseIndex}` : undefined); expect(await Promise.all(parts.map((item) => bytes(item.targetPath))), selectedPhase).toEqual(expectedRolledBack === 0 ? ["new-record", "new-generation"] : expectedRolledBack === 1 ? ["new-record", "old-generation"] : old);
      const journal = await readTransactionJournal(store, operationId); expect(journal.ok, `${selectedPhase}.journal`).toBe(!terminal || selectedPhase !== "after-retirement"); const receipt = await readTransactionReceipt(store, operationId); expect(receipt.ok ? receipt.value?.outcome : "invalid", selectedPhase).toBe(terminal ? "rolled-back" : undefined);
      for (const directory of new Set(parts.map((item) => path.dirname(item.targetPath)))) expect((await fs.readdir(directory)).filter((name) => name.includes(".tmp-")).length, selectedPhase).toBe(0);
      if (!terminal) { expect(await recoverTransaction({ store, operationId, action: "complete", confirmedProducerSchema: codec.schema, confirmedProducerVersion: codec.version, confirmedPlanDigest: preview.value.planDigest, confirmedConfirmationDigest: preview.value.confirmationDigest, registry: registry(), lease: held })).toMatchObject({ ok: false, code: "invalid-recovery" }); expect(await recovery(store, operationId, "rollback", codec, held)).toMatchObject({ ok: true, value: { outcome: "rolled-back" } }); }
      expect(await Promise.all(parts.map((item) => bytes(item.targetPath)))).toEqual(old); await releaseLifecycleLocks(held);
    }
  });

  it("restores authentic external backups with rollback authority and rejects forged evidence and alias retargets", async () => {
    const store = await fixture(); const external = path.join(path.dirname(store.profileRoot), "external"); await fs.mkdir(external); const target = path.join(external, "settings.json"); const calls: string[] = [];
    const externalCodec: TransactionProducerCodec = { ...codec, schema: "test.external", authorizeExternal(context) { calls.push(`${context.operationId}:${context.mutation}`); return (context.participant.producerEvidence as { token?: string }).token === "trusted" ? { ok: true, value: undefined } : { ok: false, code: "authority", message: "invalid" }; } };
    const absentStage = await stage(store, "external.stage", "new"); const absent: TransactionParticipant = { kind: "test.settings", key: "settings", ownerKey: "producer", scopeKey: "checkout", targetPath: target, targetClass: "external", precondition: { state: "absent" }, stagedPath: absentStage.path, stagedDigest: absentStage.digest, rollback: { kind: "delete-new-target" }, producerEvidence: { token: "trusted" } }; const absentPlan = await prepared(store, "external", [absent], externalCodec); const absentLease = await lease(store, "external");
    expect(await executeTransaction(store, absentPlan, { lease: absentLease, faults: { hit(phase) { if (phase === "after-replacement") throw new Error("pending"); } } })).toMatchObject({ state: "pending-recovery", completed: 1 }); expect(await recovery(store, "external", "rollback", externalCodec, absentLease)).toMatchObject({ ok: true, value: { outcome: "rolled-back" } }); expect(await bytes(target)).toBeUndefined(); await releaseLifecycleLocks(absentLease);
    await fs.writeFile(target, "authentic-old"); const presentStage = await stage(store, "external-present.stage", "authentic-new"); const backup = await stage(store, "external-present.backup", "authentic-old"); const present: TransactionParticipant = { ...absent, key: "present", precondition: { state: "present", digest: sha256(Buffer.from("authentic-old")) }, stagedPath: presentStage.path, stagedDigest: presentStage.digest, rollback: { kind: "restore-backup", path: backup.path, digest: backup.digest } }; const presentPlan = await prepared(store, "external-present", [present], externalCodec); const presentLease = await lease(store, "external-present");
    expect(await executeTransaction(store, presentPlan, { lease: presentLease, faults: { hit(phase) { if (phase === "after-replacement") throw new Error("pending"); } } })).toMatchObject({ state: "pending-recovery", completed: 1 }); expect(await bytes(target)).toBe("authentic-new"); expect(await recovery(store, "external-present", "rollback", externalCodec, presentLease)).toMatchObject({ ok: true, value: { outcome: "rolled-back" } }); expect(await bytes(target)).toBe("authentic-old"); await releaseLifecycleLocks(presentLease); expect(calls).toEqual(["external:replace", "external:delete", "external-present:replace", "external-present:rollback"]);
    const authorizeStage = await stage(store, "authorize-race.stage", "authorize-new"); const authorizeCodec: TransactionProducerCodec = { ...externalCodec, schema: "test.external-authorize-race", async authorizeExternal(context) { if (context.mutation === "replace") await fs.writeFile(context.participant.targetPath, "authorize-intruder"); return { ok: true, value: undefined }; } }; const authorizePlan = await prepared(store, "external-authorize-race", [{ ...present, key: "authorize-race", stagedPath: authorizeStage.path, stagedDigest: authorizeStage.digest, precondition: { state: "present", digest: sha256(Buffer.from("authentic-old")) } }], authorizeCodec); const authorizeLease = await lease(store, "external-authorize-race"); expect(await executeTransaction(store, authorizePlan, { lease: authorizeLease })).toMatchObject({ state: "failed-before-commit", receipt: { failureCategory: "stale-precondition" } }); expect(await bytes(target)).toBe("authorize-intruder"); await releaseLifecycleLocks(authorizeLease); await fs.writeFile(target, "authentic-old");
    const deniedStage = await stage(store, "denied.stage", "denied"); const deniedPlan = await prepared(store, "external-denied", [{ ...absent, key: "denied", stagedPath: deniedStage.path, stagedDigest: deniedStage.digest, precondition: { state: "present", digest: sha256(Buffer.from("authentic-old")) }, rollback: { kind: "restore-backup", path: backup.path, digest: backup.digest }, producerEvidence: { token: "FORGED_AUTHORITY_CANARY" } }], externalCodec); const deniedLease = await lease(store, "external-denied"); expect(await executeTransaction(store, deniedPlan, { lease: deniedLease })).toMatchObject({ state: "failed-before-commit", receipt: { failureCategory: "storage-failure" } }); expect(await bytes(target)).toBe("authentic-old"); await releaseLifecycleLocks(deniedLease);
    const aliasStage = await stage(store, "alias.stage", "outside-write"); const aliasPlan = await prepared(store, "external-alias", [{ ...absent, key: "alias", stagedPath: aliasStage.path, stagedDigest: aliasStage.digest, precondition: { state: "present", digest: sha256(Buffer.from("authentic-old")) }, rollback: { kind: "restore-backup", path: backup.path, digest: backup.digest } }], externalCodec); const authentic = `${external}-authentic`; const outside = path.join(path.dirname(store.profileRoot), "outside"); await fs.mkdir(outside); await fs.writeFile(path.join(outside, "canary.txt"), "outside-canary"); const probe = path.join(path.dirname(store.profileRoot), "alias-probe"); let nativeAlias = true; try { await fs.symlink(outside, probe, process.platform === "win32" ? "junction" : "dir"); await fs.rm(probe); } catch { nativeAlias = false; await fs.rm(probe, { recursive: true, force: true }); }
    if (nativeAlias) { const aliasLease = await lease(store, "external-alias"); let retargeted = false; let movedTemporary: string | undefined; expect(await executeTransaction(store, aliasPlan, { lease: aliasLease, faults: { async hit(phase) { if (!retargeted && phase === "before-replacement") { retargeted = true; await fs.rename(external, authentic); const adjacent = (await fs.readdir(authentic)).filter((name) => name.startsWith("settings.json.tmp-")); expect(adjacent).toHaveLength(1); movedTemporary = path.join(outside, adjacent[0]!); await fs.rename(path.join(authentic, adjacent[0]!), movedTemporary); await fs.symlink(outside, external, process.platform === "win32" ? "junction" : "dir"); } } } }), "native parent retarget").toMatchObject({ state: "failed-before-commit", receipt: { failureCategory: "storage-failure" } }); expect(retargeted).toBe(true); expect(movedTemporary).toBeDefined(); expect(await fs.readFile(path.join(outside, "canary.txt"), "utf8")).toBe("outside-canary"); expect(await exists(path.join(outside, "settings.json"))).toBe(false); expect(await fs.readFile(movedTemporary!, "utf8")).toBe("outside-write"); await releaseLifecycleLocks(aliasLease);
      const staticStage = await stage(store, "static-alias.stage", "static"); expect(await prepareTransaction({ store, codec: externalCodec, operationId: "static-alias", confirmationSummary: { label: "static-alias" }, participants: [{ ...absent, key: "static", targetPath: path.join(external, "static.json"), stagedPath: staticStage.path, stagedDigest: staticStage.digest }] })).toMatchObject({ ok: false, code: "invalid-participant" }); }
  });

  it("serializes deterministic same-record and different-record contenders at the profile lock", async () => {
    for (const sameRecord of [true, false]) { const store = await fixture(); const winnerPart = await participant(store, `${sameRecord ? "same" : "different"}-winner`, "winner"); const contenderRaw = await participant(store, `${sameRecord ? "same" : "different"}-contender`, "contender"); const contenderPart = sameRecord ? { ...contenderRaw, targetPath: winnerPart.targetPath } : contenderRaw; const winnerId = `${sameRecord ? "same" : "different"}-winner`; const contenderId = `${sameRecord ? "same" : "different"}-contender`; const winnerPlan = await prepared(store, winnerId, [winnerPart]); const contenderPlan = await prepared(store, contenderId, [contenderPart]); const winnerLease = await lease(store, winnerId); const entered = deferred<void>(); const release = deferred<void>(); let blocked = false;
      const winning = executeTransaction(store, winnerPlan, { lease: winnerLease, faults: { async hit(phase) { if (!blocked && phase === "before-replacement") { blocked = true; entered.resolve(); await release.promise; } } } }); await entered.promise;
      expect(await acquireLifecycleLocks({ store, operationId: contenderId, identities: lockVector(store) }), `${sameRecord}.busy`).toMatchObject({ ok: false, code: "lock-busy" }); expect(await readTransactionReceipt(store, contenderId)).toEqual({ ok: true, value: undefined }); release.resolve(); expect(await winning).toMatchObject({ state: "committed" }); await releaseLifecycleLocks(winnerLease);
      const contenderLease = await lease(store, contenderId); const result = await executeTransaction(store, contenderPlan, { lease: contenderLease }); expect(result, `${sameRecord}.result`).toMatchObject(sameRecord ? { state: "failed-before-commit", receipt: { failureCategory: "stale-precondition" } } : { state: "committed" }); expect(await bytes(winnerPart.targetPath)).toBe("winner"); expect(await bytes(contenderRaw.targetPath)).toBe(sameRecord ? undefined : "contender"); const contenderReceipt = await readTransactionReceipt(store, contenderId); expect(contenderReceipt.ok ? contenderReceipt.value?.outcome : "invalid").toBe(sameRecord ? "failed-before-commit" : "committed"); await releaseLifecycleLocks(contenderLease); }
  });

  it("rejects persisted mutation canaries across absent, present-backup, generation, external, and failed-receipt variants", async () => {
    async function writeCanonicalFile(candidate: string, value: unknown) { const encoded = canonicalJsonBytes(value); if (!encoded.ok) throw new Error(encoded.message); await fs.writeFile(candidate, encoded.value); }
    const variants = ["absent", "present", "generation", "external"] as const;
    for (const variant of variants) { const store = await fixture(); const operationId = `variant-${variant}`; let p = await participant(store, operationId, `new-${variant}`, variant === "generation" ? "final-generation" : undefined); let selected = codec;
      if (variant === "present") { await fs.writeFile(p.targetPath, "old-present"); const backup = await stage(store, `${operationId}.backup`, "old-present"); p = { ...p, precondition: { state: "present", digest: sha256(Buffer.from("old-present")) }, rollback: { kind: "restore-backup", path: backup.path, digest: backup.digest } }; }
      if (variant === "external") { const parent = path.join(path.dirname(store.profileRoot), `external-${operationId}`); await fs.mkdir(parent); const staged = await stage(store, `${operationId}.external`, "new-external"); p = { kind: "test.external", key: operationId, ownerKey: "producer", scopeKey: "external", targetPath: path.join(parent, "settings.json"), targetClass: "external", precondition: { state: "absent" }, stagedPath: staged.path, stagedDigest: staged.digest, rollback: { kind: "delete-new-target" }, producerEvidence: { token: "trusted" } }; selected = { ...codec, schema: "test.variant-external", authorizeExternal: () => ({ ok: true, value: undefined }) }; }
      const plan = await prepared(store, operationId, [p], selected); const held = await lease(store, operationId); expect(await executeTransaction(store, plan, { lease: held, faults: { hit(phase) { if (phase === "after-replacement") throw new Error("pending"); } } })).toMatchObject({ state: "pending-recovery", completed: 1 }); const file = path.join(store.journalsRoot, `${operationId}.json`); const original = await fs.readFile(file); const parsed = JSON.parse(original.toString()) as Record<string, unknown>;
      const mutations: readonly (readonly [string, (value: Record<string, unknown>) => void])[] = [["missing", (value) => { delete value.format; }], ["extra", (value) => { value.extra = `${variant.toUpperCase()}_EXTRA_CANARY`; }], ["malformed", (value) => { value.formatVersion = "MALFORMED_CANARY"; }], ["evidence", (value) => { ((value.participants as Record<string, unknown>[])[0]!.targetEvidence as Record<string, unknown>).path = path.join(store.profileRoot, `${variant.toUpperCase()}_EVIDENCE_CANARY`); }]];
      for (const [name, mutate] of mutations) { const changed = structuredClone(parsed); mutate(changed); if (variant === "present" && name === "evidence") ((changed.participants as Record<string, unknown>[])[0]!.backupEvidence as Record<string, unknown>).path = path.join(store.stagingRoot, "PRESENT_BACKUP_CANARY"); if (variant === "generation" && name === "malformed") delete (changed.participants as Record<string, unknown>[])[0]!.generationId; if (variant === "external" && name === "malformed") (changed.participants as Record<string, unknown>[])[0]!.targetClass = "EXTERNAL_DISCRIMINANT_CANARY"; await writeCanonicalFile(file, changed); const result = await readTransactionJournal(store, operationId); expect(result, `${variant}.${name}`).toMatchObject({ ok: false, code: "invalid-journal" }); expect(JSON.stringify(result)).not.toContain("CANARY"); }
      await fs.writeFile(file, Buffer.concat([original, Buffer.from("\n")])); expect(await readTransactionJournal(store, operationId)).toMatchObject({ ok: false, code: "invalid-journal" }); await fs.writeFile(file, Buffer.alloc(1024 * 1024 + 1)); expect(await readTransactionJournal(store, operationId)).toMatchObject({ ok: false, code: "invalid-journal" }); await fs.writeFile(file, original); expect(await readTransactionJournal(store, operationId)).toMatchObject({ ok: true, value: { completed: 1 } }); expect((await fs.readFile(file, "utf8"))).not.toContain("CANARY"); await releaseLifecycleLocks(held); }
    const store = await fixture(); const operationId = "variant-failed-receipt"; const plan = await prepared(store, operationId, [await participant(store, operationId, "never")]); const held = await lease(store, operationId); const controller = new AbortController(); controller.abort(); expect(await executeTransaction(store, plan, { lease: held, signal: controller.signal })).toMatchObject({ state: "failed-before-commit", receipt: { failureCategory: "cancelled" } }); const receiptFile = path.join(store.receiptsRoot, `${operationId}.json`); const receiptOriginal = await fs.readFile(receiptFile); const receipt = JSON.parse(receiptOriginal.toString()) as Record<string, unknown>;
    for (const [name, changed] of [["missing", Object.fromEntries(Object.entries(receipt).filter(([key]) => key !== "failureCategory"))], ["extra", { ...receipt, extra: "FAILED_RECEIPT_EXTRA_CANARY" }], ["malformed", { ...receipt, failureCategory: "FAILED_CATEGORY_CANARY" }], ["summary", { ...receipt, confirmationSummary: { label: operationId, extra: "FAILED_SUMMARY_CANARY" } }]] as const) { await writeCanonicalFile(receiptFile, changed); const result = await readTransactionReceipt(store, operationId); expect(result, name).toMatchObject({ ok: false, code: "invalid-receipt" }); expect(JSON.stringify(result)).not.toContain("CANARY"); } await fs.writeFile(receiptFile, Buffer.concat([receiptOriginal, Buffer.from("\n")])); expect(await readTransactionReceipt(store, operationId)).toMatchObject({ ok: false, code: "invalid-data" }); await fs.writeFile(receiptFile, Buffer.alloc(1024 * 1024 + 1)); expect(await readTransactionReceipt(store, operationId)).toMatchObject({ ok: false, code: "invalid-data" }); await fs.writeFile(receiptFile, receiptOriginal); expect(await readTransactionReceipt(store, operationId)).toMatchObject({ ok: true, value: { outcome: "failed-before-commit" } }); expect((await fs.readFile(receiptFile, "utf8"))).not.toContain("CANARY"); await releaseLifecycleLocks(held);
  });

  it("uses exact journal/receipt/lock parsers and rejects field, relationship, and owner-generation mutations", async () => {
    const store = await fixture(); let parserPresent = await participant(store, "parser-a", "a"); await fs.writeFile(parserPresent.targetPath, "old-a"); const parserBackup = await stage(store, "parser-a.backup", "old-a"); parserPresent = { ...parserPresent, precondition: { state: "present", digest: sha256(Buffer.from("old-a")) }, rollback: { kind: "restore-backup", path: parserBackup.path, digest: parserBackup.digest } }; const plan = await prepared(store, "parser", [parserPresent, await participant(store, "parser-b", "b", "parser-generation")]); const held = await lease(store, "parser");
    expect(await executeTransaction(store, plan, { lease: held, faults: { hit(phase, index) { if (phase === "before-temp-write" && index === 1) throw new Error("pending"); } } })).toMatchObject({ state: "pending-recovery", completed: 1 });
    const journalFile = path.join(store.journalsRoot, "parser.json"); const original = await fs.readFile(journalFile); const parsed = JSON.parse(original.toString()) as Record<string, unknown>;
    async function writeCanonical(candidate: string, value: unknown) { const bytes = canonicalJsonBytes(value); if (!bytes.ok) throw new Error(bytes.message); await fs.writeFile(candidate, bytes.value); }
    const journalMutations: readonly (readonly [string, (value: Record<string, unknown>) => void])[] = [
      ...Object.keys(parsed).map((key): readonly [string, (value: Record<string, unknown>) => void] => [`missing.${key}`, (value) => { delete value[key]; }]),
      ["extra", (value) => { value.extra = "JOURNAL_EXTRA_CANARY"; }], ["format", (value) => { value.format = "future-journal"; }], ["version", (value) => { value.formatVersion = 2; }], ["state", (value) => { value.state = "future-state"; }],
      ["summary", (value) => { value.confirmationSummary = { label: "parser", extra: "SUMMARY_CANARY" }; }], ["completed-over", (value) => { value.completed = 3; }], ["rollback-over", (value) => { value.state = "rolling-back"; value.rolledBack = 2; }], ["rollback-without-state", (value) => { value.rolledBack = 1; }],
      ["lock-order", (value) => { (value.lockBindings as unknown[]).reverse(); }], ["lock-duplicate", (value) => { (value.lockBindings as unknown[])[1] = structuredClone((value.lockBindings as unknown[])[0]); }], ["required-lock-duplicate", (value) => { (value.requiredLocks as unknown[])[1] = structuredClone((value.requiredLocks as unknown[])[0]); }],
      ["precondition-discriminant", (value) => { ((value.participants as Record<string, unknown>[])[0]!.precondition as Record<string, unknown>).state = "PRESENT_CANARY"; }], ["rollback-discriminant", (value) => { ((value.participants as Record<string, unknown>[])[0]!.rollback as Record<string, unknown>).kind = "RESTORE_CANARY"; }],
      ["path-evidence", (value) => { ((value.participants as Record<string, unknown>[])[0]!.targetEvidence as Record<string, unknown>).path = path.join(store.profileRoot, "PATH_EVIDENCE_CANARY"); }], ["evidence-extra", (value) => { ((value.participants as Record<string, unknown>[])[0]!.stagedEvidence as Record<string, unknown>).extra = "EVIDENCE_CANARY"; }],
      ["generation-relationship", (value) => { const p = (value.participants as Record<string, unknown>[])[0]!; p.targetClass = "generation"; p.generationId = "FORGED_GENERATION_CANARY"; }],
    ];
    for (const [name, mutate] of journalMutations) { const changed = structuredClone(parsed); mutate(changed); await writeCanonical(journalFile, changed); const result = await readTransactionJournal(store, "parser"); expect(result, name).toMatchObject({ ok: false, code: "invalid-journal" }); expect(JSON.stringify(result), name).not.toContain("CANARY"); }
    const malformedParticipant: Record<string, unknown> = { kind: "INVALID_KIND", key: "", ownerKey: "bad owner", scopeKey: "", targetPath: "relative", targetClass: "invalid-class", precondition: null, stagedPath: "relative", stagedDigest: "bad-digest", rollback: null, producerEvidence: "PARTICIPANT_EVIDENCE_CANARY", targetEvidence: null, stagedEvidence: null, backupEvidence: null, generationId: "invalid generation" };
    for (const [participantIndex, rawParticipant] of (parsed.participants as Record<string, unknown>[]).entries()) {
      for (const key of Object.keys(rawParticipant)) { const changed = structuredClone(parsed); delete (changed.participants as Record<string, unknown>[])[participantIndex]![key]; await writeCanonical(journalFile, changed); expect(await readTransactionJournal(store, "parser"), `participant.${participantIndex}.missing.${key}`).toMatchObject({ ok: false, code: "invalid-journal" }); }
      for (const key of Object.keys(rawParticipant)) { const changed = structuredClone(parsed); (changed.participants as Record<string, unknown>[])[participantIndex]![key] = malformedParticipant[key]; await writeCanonical(journalFile, changed); const result = await readTransactionJournal(store, "parser"); expect(result, `participant.${participantIndex}.malformed.${key}`).toMatchObject({ ok: false, code: "invalid-journal" }); expect(JSON.stringify(result)).not.toContain("CANARY"); }
      const changed = structuredClone(parsed); (changed.participants as Record<string, unknown>[])[participantIndex]!.extra = "PARTICIPANT_EXTRA_CANARY"; await writeCanonical(journalFile, changed); const result = await readTransactionJournal(store, "parser"); expect(result, `participant.${participantIndex}.extra`).toMatchObject({ ok: false, code: "invalid-journal" }); expect(JSON.stringify(result)).not.toContain("CANARY");
    }
    const malformedBinding: Record<string, unknown> = { kind: "invalid-kind", key: "", nonce: "z".repeat(32), generation: "z".repeat(32) };
    for (const [bindingIndex, rawBinding] of (parsed.lockBindings as Record<string, unknown>[]).entries()) {
      for (const key of Object.keys(rawBinding)) { const changed = structuredClone(parsed); delete (changed.lockBindings as Record<string, unknown>[])[bindingIndex]![key]; await writeCanonical(journalFile, changed); expect(await readTransactionJournal(store, "parser"), `binding.${bindingIndex}.missing.${key}`).toMatchObject({ ok: false, code: "invalid-journal" }); }
      for (const key of Object.keys(rawBinding)) { const changed = structuredClone(parsed); (changed.lockBindings as Record<string, unknown>[])[bindingIndex]![key] = malformedBinding[key]; await writeCanonical(journalFile, changed); expect(await readTransactionJournal(store, "parser"), `binding.${bindingIndex}.malformed.${key}`).toMatchObject({ ok: false, code: "invalid-journal" }); }
      const changed = structuredClone(parsed); (changed.lockBindings as Record<string, unknown>[])[bindingIndex]!.extra = "LOCK_BINDING_EXTRA_CANARY"; await writeCanonical(journalFile, changed); const result = await readTransactionJournal(store, "parser"); expect(result, `binding.${bindingIndex}.extra`).toMatchObject({ ok: false, code: "invalid-journal" }); expect(JSON.stringify(result)).not.toContain("CANARY");
    }
    await fs.writeFile(journalFile, Buffer.concat([original, Buffer.from("\n")])); expect(await readTransactionJournal(store, "parser")).toMatchObject({ ok: false, code: "invalid-journal" }); await fs.writeFile(journalFile, Buffer.alloc(1024 * 1024 + 1, 0x20)); expect(await readTransactionJournal(store, "parser")).toMatchObject({ ok: false, code: "invalid-journal" });
    await writeCanonical(journalFile, { ...parsed, producerSchema: "test.unknown-canary" }); expect(await readTransactionJournal(store, "parser")).toMatchObject({ ok: true }); expect(await previewRecovery({ store, operationId: "parser", registry: registry() })).toMatchObject({ ok: false, code: "unknown-producer" });
    await fs.writeFile(journalFile, original); const preview = await previewRecovery({ store, operationId: "parser", registry: registry() }); if (!preview.ok) throw new Error(preview.message); const recovered = await recoverTransaction({ store, operationId: "parser", action: "complete", confirmedProducerSchema: "test.transaction", confirmedProducerVersion: 1, confirmedPlanDigest: preview.value.planDigest, confirmedConfirmationDigest: preview.value.confirmationDigest, registry: registry(), lease: held }); if (!recovered.ok) throw new Error(`${recovered.code}: ${recovered.message}`); expect(recovered).toMatchObject({ ok: true });
    const receiptFile = path.join(store.receiptsRoot, "parser.json"); const receiptOriginal = await fs.readFile(receiptFile); const receipt = JSON.parse(receiptOriginal.toString()) as Record<string, unknown>;
    for (const key of Object.keys(receipt)) { const changed = { ...receipt }; delete changed[key]; await writeCanonical(receiptFile, changed); expect(await readTransactionReceipt(store, "parser"), `receipt.${key}`).toMatchObject({ ok: false, code: "invalid-receipt" }); }
    for (const [name, changed] of [["extra", { ...receipt, extra: "RECEIPT_EXTRA_CANARY" }], ["completed", { ...receipt, completed: 1 }], ["failed-category", { ...receipt, outcome: "failed-before-commit", completed: 0, failureCategory: "FORGED_FAILURE_CANARY" }], ["generation", { ...receipt, generationId: "FORGED_GENERATION_CANARY" }]] as const) { await writeCanonical(receiptFile, changed); const result = await readTransactionReceipt(store, "parser"); expect(result, name).toMatchObject({ ok: false, code: "invalid-receipt" }); expect(JSON.stringify(result)).not.toContain("CANARY"); } await fs.writeFile(receiptFile, Buffer.concat([receiptOriginal, Buffer.from("\n")])); expect(await readTransactionReceipt(store, "parser")).toMatchObject({ ok: false, code: "invalid-data" }); await fs.writeFile(receiptFile, receiptOriginal);
    const ownerFile = path.join(lifecycleLockDirectory(store, { kind: "profile", key: store.profileKey }), "owner.json"); const ownerOriginal = await fs.readFile(ownerFile); const owner = JSON.parse(ownerOriginal.toString()) as Record<string, unknown>;
    for (const key of Object.keys(owner)) { const changed = { ...owner }; delete changed[key]; await writeCanonical(ownerFile, changed); expect((await validateLifecycleLockLease(store, held, "parser")).ok, `owner.missing.${key}`).toBe(false); await fs.writeFile(ownerFile, ownerOriginal); }
    const malformedOwner: Record<string, unknown> = { format: "future-lock", formatVersion: 2, operationId: "bad operation", identityKind: "invalid-kind", identityKey: "", nonce: "z".repeat(32), generation: "z".repeat(32), pid: 0, processToken: "", acquiredAt: "not-a-time", heartbeatAt: "not-a-time" };
    for (const [key, invalid] of Object.entries(malformedOwner)) { await writeCanonical(ownerFile, { ...owner, [key]: invalid }); const result = await validateLifecycleLockLease(store, held, "parser"); expect(result, `owner.malformed.${key}`).toMatchObject({ ok: false, code: "lost-lock" }); expect(JSON.stringify(result)).not.toContain("CANARY"); await fs.writeFile(ownerFile, ownerOriginal); }
    await writeCanonical(ownerFile, { ...owner, future: "LOCK_OWNER_EXTRA_CANARY" }); const lost = await validateLifecycleLockLease(store, held, "parser"); expect(lost).toMatchObject({ ok: false, code: "lost-lock" }); expect(JSON.stringify(lost)).not.toContain("CANARY"); await fs.writeFile(ownerFile, ownerOriginal);
    const predecessor = { kind: owner.identityKind, key: owner.identityKey, nonce: "1".repeat(32), generation: "2".repeat(32) }; await writeCanonical(ownerFile, { ...owner, predecessorBinding: predecessor }); expect(await validateLifecycleLockLease(store, held, "parser")).toMatchObject({ ok: true }); expect(await heartbeatLifecycleLocks(held)).toMatchObject({ ok: true }); const heartbeaten = JSON.parse(await fs.readFile(ownerFile, "utf8")) as Record<string, unknown>; expect(heartbeaten.predecessorBinding).toEqual(predecessor);
    const predecessorMutations: readonly (readonly [string, unknown])[] = [["missing-kind", { key: predecessor.key, nonce: predecessor.nonce, generation: predecessor.generation }], ["missing-key", { kind: predecessor.kind, nonce: predecessor.nonce, generation: predecessor.generation }], ["missing-nonce", { kind: predecessor.kind, key: predecessor.key, generation: predecessor.generation }], ["missing-generation", { kind: predecessor.kind, key: predecessor.key, nonce: predecessor.nonce }], ["extra", { ...predecessor, extra: "PREDECESSOR_EXTRA_CANARY" }], ["malformed", "PREDECESSOR_MALFORMED_CANARY"], ["wrong-kind", { ...predecessor, kind: "settings" }], ["wrong-key", { ...predecessor, key: "PREDECESSOR_WRONG_IDENTITY_CANARY" }], ["bad-nonce", { ...predecessor, nonce: "z".repeat(32) }], ["bad-generation", { ...predecessor, generation: "z".repeat(32) }], ["self", { kind: owner.identityKind, key: owner.identityKey, nonce: owner.nonce, generation: owner.generation }]];
    for (const [name, predecessorBinding] of predecessorMutations) { await writeCanonical(ownerFile, { ...heartbeaten, predecessorBinding }); const result = await validateLifecycleLockLease(store, held, "parser"); expect(result, `owner.predecessor.${name}`).toMatchObject({ ok: false, code: "lost-lock" }); expect(JSON.stringify(result), name).not.toContain("CANARY"); }
    await fs.writeFile(ownerFile, Buffer.concat([Buffer.from((canonicalJsonBytes(heartbeaten) as { ok: true; value: Uint8Array }).value), Buffer.from("\n")])); expect(await validateLifecycleLockLease(store, held, "parser")).toMatchObject({ ok: false, code: "lost-lock" }); await writeCanonical(ownerFile, heartbeaten);
    for (const authoritative of [receiptFile, journalFile, ...lockVector(store).map((identity) => path.join(lifecycleLockDirectory(store, identity), "owner.json"))]) { const content = await fs.readFile(authoritative).catch(() => Buffer.alloc(0)); expect(content.toString(), authoritative).not.toContain("CANARY"); } expect(await releaseLifecycleLocks(held)).toMatchObject({ ok: true });
  });

  it("detects forged/released leases, fixed-order contention, stale heartbeat identity, and invalid partial requests", async () => {
    const store = await fixture(); const held = await lease(store, "locks"); expect(await validateLifecycleLockLease(store, { ...held }, "locks")).toMatchObject({ ok: false, code: "invalid-lease" }); expect((await heartbeatLifecycleLocks(held)).ok).toBe(true);
    expect(await acquireLifecycleLocks({ store, operationId: "other", identities: [{ kind: "profile", key: store.profileKey }] })).toMatchObject({ ok: false, code: "lock-busy" });
    expect(await acquireLifecycleLocks({ store, operationId: "partial", identities: [{ kind: "profile", key: "wrong-profile" }, { kind: "settings", key: "x" }] })).toMatchObject({ ok: false, code: "invalid-lock-order" });
    expect(await releaseLifecycleLocks(held)).toMatchObject({ ok: true }); expect(await validateLifecycleLockLease(store, held, "locks")).toMatchObject({ ok: false, code: "invalid-lease" });
    const collision = lifecycleLockDirectory(store, lockVector(store)[1]!); await fs.mkdir(collision); await fs.writeFile(path.join(collision, "owner.json"), "{}"); const contenderBytes = await fs.readFile(path.join(collision, "owner.json"));
    expect(await acquireLifecycleLocks({ store, operationId: "partial-cleanup", identities: lockVector(store) })).toMatchObject({ ok: false, code: "ambiguous-lock" });
    await expect(fs.stat(lifecycleLockDirectory(store, lockVector(store)[0]!))).rejects.toMatchObject({ code: "ENOENT" }); expect(await fs.readFile(path.join(collision, "owner.json"))).toEqual(contenderBytes); await fs.rm(collision, { recursive: true });
  });

  it("reports lost-lock on heartbeat ownership mutation and preserves replacement bytes", async () => {
    const store = await fixture(); const held = await lease(store, "heartbeat-identity-change"); const directory = lifecycleLockDirectory(store, lockVector(store)[0]!); const ownerFile = path.join(directory, "owner.json"); const owner = JSON.parse(await fs.readFile(ownerFile, "utf8")) as Record<string, unknown>; const replacement = canonicalJsonBytes({ ...owner, nonce: "0".repeat(32) }); if (!replacement.ok) throw new Error(replacement.message); await fs.writeFile(ownerFile, replacement.value); const entries = await fs.readdir(directory);
    expect(await heartbeatLifecycleLocks(held)).toMatchObject({ ok: false, code: "lost-lock" }); expect(await fs.readFile(ownerFile)).toEqual(Buffer.from(replacement.value)); expect(await fs.readdir(directory)).toEqual(entries);
  });

  it("reports lost-lock on release directory replacement and preserves replacement ownership", async () => {
    const store = await fixture(); const held = await lease(store, "release-identity-change"); const directory = lifecycleLockDirectory(store, lockVector(store)[0]!); const displaced = `${directory}.displaced`; const originalOwner = JSON.parse(await fs.readFile(path.join(directory, "owner.json"), "utf8")) as Record<string, unknown>; const replacement = canonicalJsonBytes({ ...originalOwner, generation: "0".repeat(32) }); if (!replacement.ok) throw new Error(replacement.message); await fs.rename(directory, displaced); await fs.mkdir(directory); await fs.writeFile(path.join(directory, "owner.json"), replacement.value); const entries = await fs.readdir(directory);
    expect(await releaseLifecycleLocks(held)).toMatchObject({ ok: false, code: "lost-lock" }); expect(await fs.readFile(path.join(directory, "owner.json"))).toEqual(Buffer.from(replacement.value)); expect(await fs.readdir(directory)).toEqual(entries); expect(await exists(displaced)).toBe(true);
  });

  it("proves repeated crash-window takeover, recovery, and receipt truth with exactly three bounded launches", async () => {
    const base = await fs.mkdtemp(path.join(os.tmpdir(), "picc-fresh-")); roots.push(base); if (process.platform !== "win32") await fs.chmod(base, 0o700); const profile = path.join(base, "profile");
    const pendingScript = String.raw`
      import { promises as fs } from "node:fs"; import path from "node:path";
      import { createLifecycleLocations } from "./src/plugin-lifecycle/locations.ts";
      import { establishOwnedStateStore, ownedRecordPartition, sha256 } from "./src/plugin-lifecycle/state-store.ts";
      import { acquireLifecycleLocks } from "./src/plugin-lifecycle/locks.ts";
      import { prepareTransaction, executeTransaction } from "./src/plugin-lifecycle/transaction.ts";
      const locations=createLifecycleLocations({homeDir:process.env.HOME_DIR,profilePath:process.env.PROFILE_DIR,platform:process.platform==="win32"?"win32":"posix"}); if(!locations.ok) throw Error("locations");
      const established=await establishOwnedStateStore(locations.value,process.env.HOME_DIR); if(!established.ok) throw Error(established.message); const store=established.value;
      const partition=ownedRecordPartition(store,"producer","user"); if(!partition.ok) throw Error(partition.message); await fs.mkdir(partition.value,{recursive:true,mode:0o700});
      const bytes=Buffer.from("fresh"); const staged=path.join(store.stagingRoot,"fresh.stage"); await fs.writeFile(staged,bytes,{flag:"wx",mode:0o600});
      const requiredLocks=(_s,ps)=>({ok:true,value:[{kind:"profile",key:path.basename(path.dirname(path.dirname(ps[0].stagedPath)))},{kind:"checkout",key:"checkout-main"},{kind:"settings",key:"settings-user"}]});
      const codec={schema:"test.transaction",version:1,decodeSummary:v=>({ok:true,value:v}),validatePlan:()=>({ok:true,value:undefined}),requiredLocks};
      const made=await prepareTransaction({store,codec,operationId:"fresh-op",confirmationSummary:{label:"fresh-op"},participants:[{kind:"test.record",key:"fresh",ownerKey:"producer",scopeKey:"user",targetPath:path.join(partition.value,"fresh.json"),targetClass:"owned",precondition:{state:"absent"},stagedPath:staged,stagedDigest:sha256(bytes),rollback:{kind:"delete-new-target"},producerEvidence:{key:"fresh"}}]}); if(!made.ok) throw Error(made.message);
      const locked=await acquireLifecycleLocks({store,operationId:"fresh-op",identities:requiredLocks(null,made.value.participants).value}); if(!locked.ok) throw Error(locked.message);
      const outcome=await executeTransaction(store,made.value,{lease:locked.value,faults:{hit(phase){if(phase==="after-replacement") throw Error("stop");}}}); process.stdout.write(JSON.stringify(outcome));
    `;
    let childLaunches = 0;
    async function child(script: string): Promise<string> {
      childLaunches += 1; const launched = spawn(process.execPath, ["--import", "tsx", "--input-type=module", "-e", script], { cwd: process.cwd(), env: { ...process.env, HOME_DIR: base, PROFILE_DIR: profile }, stdio: ["ignore", "pipe", "pipe"] }); let stdout = ""; let stderr = ""; launched.stdout.on("data", (chunk: Buffer) => { stdout += chunk.toString(); }); launched.stderr.on("data", (chunk: Buffer) => { stderr += chunk.toString(); });
      const exit = new Promise<void>((resolve, reject) => { launched.once("error", reject); launched.once("exit", (code) => code === 0 ? resolve() : reject(new Error(`child ${code}: ${stderr}`))); }); const ceiling = setTimeout(() => launched.kill(), 10_000); try { await exit; return stdout; } finally { clearTimeout(ceiling); if (launched.exitCode === null) launched.kill(); await new Promise<void>((resolve) => launched.exitCode === null ? launched.once("exit", () => resolve()) : resolve()); }
    }
    expect(JSON.parse(await child(pendingScript))).toMatchObject({ state: "pending-recovery", completed: 1 });
    const locations = createLifecycleLocations({ homeDir: base, profilePath: profile, platform: process.platform === "win32" ? "win32" : "posix" }); if (!locations.ok) throw new Error("locations"); const established = await establishOwnedStateStore(locations.value, base); if (!established.ok) throw new Error(established.message); const store = established.value;
    const pending = await previewRecovery({ store, operationId: "fresh-op", registry: registry() }); expect(pending).toMatchObject({ ok: true, value: { completed: 1 } }); if (!pending.ok) return; const journalBeforeTakeover = await readTransactionJournal(store, "fresh-op"); if (!journalBeforeTakeover.ok) throw new Error(journalBeforeTakeover.message); const originalBindings = journalBeforeTakeover.value.lockBindings;
    const takeoverScript = String.raw`
      import { createLifecycleLocations } from "./src/plugin-lifecycle/locations.ts"; import { establishOwnedStateStore } from "./src/plugin-lifecycle/state-store.ts"; import { acquireLifecycleLocks } from "./src/plugin-lifecycle/locks.ts";
      const l=createLifecycleLocations({homeDir:process.env.HOME_DIR,profilePath:process.env.PROFILE_DIR,platform:process.platform==="win32"?"win32":"posix"}); if(!l.ok) throw Error("locations"); const s=await establishOwnedStateStore(l.value,process.env.HOME_DIR); if(!s.ok) throw Error(s.message);
      const identities=[{kind:"profile",key:s.value.profileKey},{kind:"checkout",key:"checkout-main"},{kind:"settings",key:"settings-user"}]; const taken=await acquireLifecycleLocks({store:s.value,operationId:"fresh-op",identities,expectedRecoveryOperationId:"fresh-op"}); if(!taken.ok) throw Error(taken.code+":"+taken.message); process.stdout.write(JSON.stringify(taken.value.bindings));
    `;
    const childBindings = JSON.parse(await child(takeoverScript)) as unknown[]; expect(childBindings).toHaveLength(3); const replacementOwners = await Promise.all(lockVector(store).map((identity) => fs.readFile(path.join(lifecycleLockDirectory(store, identity), "owner.json"), "utf8").then((value) => JSON.parse(value) as Record<string, unknown>))); expect(replacementOwners.map((owner) => owner.predecessorBinding)).toEqual(originalBindings); expect(replacementOwners.map((owner) => ({ kind: owner.identityKind, key: owner.identityKey, nonce: owner.nonce, generation: owner.generation }))).toEqual(childBindings);
    const recoveryBase = { store, operationId: "fresh-op", expectedRecoveryOperationId: "fresh-op", processProbe: { observe: async () => ({ state: "absent" as const }) } };
    expect(await acquireLifecycleLocks({ ...recoveryBase, identities: lockVector(store).slice(0, 2) })).toMatchObject({ ok: false, code: "ambiguous-lock" });
    expect(await acquireLifecycleLocks({ ...recoveryBase, identities: [lockVector(store)[0]!, lockVector(store)[1]!, { kind: "settings", key: "wrong" }] })).toMatchObject({ ok: false, code: "ambiguous-lock" });
    expect(await acquireLifecycleLocks({ ...recoveryBase, identities: [lockVector(store)[0]!, lockVector(store)[2]!, lockVector(store)[1]!] })).toMatchObject({ ok: false, code: "invalid-lock-order" });
    expect(await acquireLifecycleLocks({ ...recoveryBase, identities: lockVector(store), processProbe: { observe: async () => ({ state: "live" as const, processToken: "reused" }) } })).toMatchObject({ ok: false, code: "ambiguous-lock" });
    expect(await acquireLifecycleLocks({ ...recoveryBase, identities: lockVector(store), processProbe: { observe: async () => ({ state: "ambiguous" as const, reason: "unknown" }) } })).toMatchObject({ ok: false, code: "ambiguous-lock" });
    const profileOwner = path.join(lifecycleLockDirectory(store, lockVector(store)[0]!), "owner.json"); const ownerBytes = await fs.readFile(profileOwner); const owner = JSON.parse(ownerBytes.toString()) as Record<string, unknown>; const missingPredecessor = { ...owner }; delete missingPredecessor.predecessorBinding; const missingBytes = canonicalJsonBytes(missingPredecessor); if (!missingBytes.ok) throw new Error(missingBytes.message); await fs.writeFile(profileOwner, missingBytes.value); expect(await acquireLifecycleLocks({ ...recoveryBase, identities: lockVector(store) })).toMatchObject({ ok: false, code: "ambiguous-lock" }); await fs.writeFile(profileOwner, ownerBytes);
    const wrongOwner = canonicalJsonBytes({ ...owner, nonce: "0".repeat(32), predecessorBinding: { ...(owner.predecessorBinding as Record<string, unknown>), nonce: "0".repeat(32) } }); if (!wrongOwner.ok) throw new Error(wrongOwner.message); await fs.writeFile(profileOwner, wrongOwner.value);
    const wrongResult = await acquireLifecycleLocks({ ...recoveryBase, identities: lockVector(store) }); expect(wrongResult).toMatchObject({ ok: false, code: "ambiguous-lock" }); expect(JSON.stringify(wrongResult)).not.toContain("CANARY"); await fs.writeFile(profileOwner, ownerBytes);
    const journalFile = path.join(store.journalsRoot, "fresh-op.json"); const journalBytes = await fs.readFile(journalFile); await fs.writeFile(journalFile, "{}"); expect(await acquireLifecycleLocks({ ...recoveryBase, identities: lockVector(store) })).toMatchObject({ ok: false, code: "ambiguous-lock" }); await fs.writeFile(journalFile, journalBytes);
    const lockDirectories = lockVector(store).map((identity) => lifecycleLockDirectory(store, identity)); const ownerFiles = lockDirectories.map((directory) => path.join(directory, "owner.json")); const exactOldVector = await Promise.all(ownerFiles.map((candidate) => fs.readFile(candidate))); const exactOldIdentities = await Promise.all(lockDirectories.map(async (directory) => { const stat = await fs.lstat(directory, { bigint: true }); return { dev: stat.dev, ino: stat.ino }; })); let probeCalls = 0;
    expect(await acquireLifecycleLocks({ ...recoveryBase, identities: lockVector(store), processProbe: { observe: async () => { probeCalls += 1; return probeCalls === 5 ? { state: "ambiguous" as const, reason: "deterministic later-member failure" } : { state: "absent" as const }; } } })).toMatchObject({ ok: false, code: "ambiguous-lock" }); expect(probeCalls).toBe(5); expect(await Promise.all(ownerFiles.map((candidate) => fs.readFile(candidate)))).toEqual(exactOldVector); expect(await Promise.all(lockDirectories.map(async (directory) => { const stat = await fs.lstat(directory, { bigint: true }); return { dev: stat.dev, ino: stat.ino }; }))).toEqual(exactOldIdentities);
    const takeover = await acquireLifecycleLocks({ store, operationId: "fresh-op", identities: lockVector(store), expectedRecoveryOperationId: "fresh-op" }); if (!takeover.ok) throw new Error(`${takeover.code}: ${takeover.message}`); const repeatedOwners = await Promise.all(lockVector(store).map((identity) => fs.readFile(path.join(lifecycleLockDirectory(store, identity), "owner.json"), "utf8").then((value) => JSON.parse(value) as Record<string, unknown>))); expect(repeatedOwners.map((owner) => owner.predecessorBinding)).toEqual(originalBindings); expect(repeatedOwners.map((owner) => ({ kind: owner.identityKind, key: owner.identityKey, nonce: owner.nonce, generation: owner.generation }))).toEqual(takeover.value.bindings);
    expect(await recoverTransaction({ store, operationId: "fresh-op", action: "complete", confirmedProducerSchema: "test.transaction", confirmedProducerVersion: 1, confirmedPlanDigest: pending.value.planDigest, confirmedConfirmationDigest: pending.value.confirmationDigest, registry: registry(), lease: takeover.value })).toMatchObject({ ok: true, value: { outcome: "committed" } }); expect(await acquireLifecycleLocks({ ...recoveryBase, identities: lockVector(store) })).toMatchObject({ ok: false, code: "ambiguous-lock" }); await releaseLifecycleLocks(takeover.value);
    const receiptScript = String.raw`import { createLifecycleLocations } from "./src/plugin-lifecycle/locations.ts"; import { establishOwnedStateStore } from "./src/plugin-lifecycle/state-store.ts"; import { readTransactionReceipt } from "./src/plugin-lifecycle/transaction.ts"; const l=createLifecycleLocations({homeDir:process.env.HOME_DIR,profilePath:process.env.PROFILE_DIR,platform:process.platform==="win32"?"win32":"posix"}); if(!l.ok) throw Error("locations"); const s=await establishOwnedStateStore(l.value,process.env.HOME_DIR); if(!s.ok) throw Error(s.message); process.stdout.write(JSON.stringify(await readTransactionReceipt(s.value,"fresh-op")));`;
    expect(JSON.parse(await child(receiptScript))).toMatchObject({ ok: true, value: { outcome: "committed", completed: 1 } }); expect(childLaunches).toBe(3);
  }, 20_000);

  it("keeps stored receipt truth when rendering and fallback output fail", async () => {
    const store = await fixture(); const plan = await prepared(store, "render", [await participant(store, "render", "ok")]); const held = await lease(store, "render"); let fallback = 0;
    expect(await executeTransaction(store, plan, { lease: held, onOutcome: () => { throw new Error("renderer"); }, fallbackOutput: () => { fallback += 1; throw new Error("output"); } })).toMatchObject({ state: "committed" }); expect(fallback).toBe(1); expect(await readTransactionReceipt(store, "render")).toMatchObject({ ok: true, value: { outcome: "committed" } }); await releaseLifecycleLocks(held);
  });
});
