import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { gzipSync } from "node:zlib";
import * as tar from "tar-stream";
import { afterEach, describe, expect, it, vi } from "vitest";
import { createLifecycleLocations } from "../src/plugin-lifecycle/locations.js";
import {
  createExecutableAdmissionGenerationCodec, createMarketplaceSnapshotTrustGrant, createOwnedMarketplaceSnapshotCodec,
  createOwnedPluginInstallationCodec, observeExecutableGenerationFile, ownedInstallationScopeKey, ownedMarketplaceSnapshotScopeKey, readOwnedAdmissionRecords,
  type MarketplaceSnapshotTrustTarget, type OwnedMarketplaceRecord, type OwnedMarketplaceSnapshotRecord, type OwnedPluginInstallationRecord,
} from "../src/plugin-lifecycle/admission.js";
import { acquireHttpsZipPlugin } from "../src/plugin-lifecycle/acquisition/archive.js";
import type { GitRunner } from "../src/plugin-lifecycle/acquisition/git.js";
import { digestArtifactEntries } from "../src/plugin-lifecycle/artifact-digest.js";
import { acquireMarketplaceRelativePlugin } from "../src/plugin-lifecycle/marketplace-generation.js";
import { pluginDependencyPosture } from "../src/plugin-lifecycle/dependencies.js";
import { createPluginSettingsTransactionCodec } from "../src/plugin-lifecycle/settings-writer.js";
import { planPluginSettingsWrite } from "../src/plugin-lifecycle/settings-plan.js";
import { readTransactionJournal, readTransactionReceipt } from "../src/plugin-lifecycle/transaction.js";
import {
  canonicalJsonBytes, createRecordEnvelope, createProducerCodecRegistry, establishOwnedStateStore, ownedRecordPartition,
  type OwnedStateStore,
} from "../src/plugin-lifecycle/state-store.js";
import {
  createTrustedLifecycleRegistry, LifecycleRecoveryService,
} from "../src/plugin-lifecycle/lifecycle-service.js";
import {
  createPluginAcquisitionAdapter, decodePluginStableSelector, deriveOwnedPluginCatalogSelections, encodePluginStableSelector, inspectAcquiredPlugin, PluginLifecycleService, pluginLifecycleProducerRegistry, pluginLifecycleTransactionRegistry, projectPluginPreviewForModel,
  type PluginInspection, type PluginLocalSnapshot, type PluginObservation,
} from "../src/plugin-lifecycle/plugin-service.js";
import type { Sha256 } from "../src/plugin-lifecycle/types.js";
import { deriveExecutableMarketplaceCatalogProjection } from "../src/util/plugin-marketplace-descriptor.js";
import { projectPluginManifest } from "../src/claude/plugin-metadata.js";
import { executableDigestForProjection } from "../src/plugin-lifecycle/admission.js";
import { loadClaudeProject } from "../src/project.js";

const roots: string[] = [];
afterEach(() => { while (roots.length > 0) fs.rmSync(roots.pop()!, { recursive: true, force: true }); });
function crc32(data: Uint8Array): number { let crc = 0xffffffff; for (const byte of data) { crc ^= byte; for (let bit = 0; bit < 8; bit++) crc = (crc & 1) === 0 ? crc >>> 1 : (crc >>> 1) ^ 0xedb88320; } return (crc ^ 0xffffffff) >>> 0; }
function zip(entries: readonly { name: string; data?: string; mode?: number }[]): Buffer { const locals: Buffer[] = []; const centrals: Buffer[] = []; let offset = 0; for (const item of entries) { const name = Buffer.from(item.name); const data = Buffer.from(item.data ?? ""); const crc = crc32(data); const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50, 0); local.writeUInt16LE(20, 4); local.writeUInt32LE(crc, 14); local.writeUInt32LE(data.length, 18); local.writeUInt32LE(data.length, 22); local.writeUInt16LE(name.length, 26); locals.push(local, name, data); const central = Buffer.alloc(46); central.writeUInt32LE(0x02014b50, 0); central.writeUInt16LE((3 << 8) | 20, 4); central.writeUInt16LE(20, 6); central.writeUInt32LE(crc, 16); central.writeUInt32LE(data.length, 20); central.writeUInt32LE(data.length, 24); central.writeUInt16LE(name.length, 28); central.writeUInt32LE(((item.mode ?? (item.name.endsWith("/") ? 0o040755 : 0o100644)) << 16) >>> 0, 38); central.writeUInt32LE(offset, 42); centrals.push(central, name); offset += local.length + name.length + data.length; } const central = Buffer.concat(centrals); const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10); end.writeUInt32LE(central.length, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...locals, central, end]); }
function pluginZip(inspection: Partial<PluginInspection> = {}, name = "tool"): Buffer { return zip([{ name: ".claude-plugin/" }, { name: ".claude-plugin/plugin.json", data: JSON.stringify({ name, version: inspection.version ?? "1.0.0", defaultEnabled: inspection.manifestDefaultEnabled ?? true, ...(inspection.dependencies === undefined ? {} : { dependencies: inspection.dependencies.map(({ itemIndex: _itemIndex, ...dependency }) => dependency) }) }) }, { name: "commands/" }, { name: "commands/run.md", data: "run" }]); }
function digest(bytes: Uint8Array): Sha256 { return `sha256:${createHash("sha256").update(bytes).digest("hex")}`; }
const COMMIT = "1".repeat(40);
const EMPTY_MANIFEST_EXECUTABLE_DIGEST = "sha256:728e9ca11459d72709a98a1df8a795ab3daad507f05717810f1133dd51b5b4e6";
function successfulGitRunner(): GitRunner { const entries = [{ path: ".claude-plugin/plugin.json", data: JSON.stringify({ name: "tool", version: "1.0.0" }) }, { path: "commands/run.md", data: "run" }]; const hashes = entries.map((_, index) => `${index + 3}`.repeat(40)); return async (request) => { if (request.args.join(" ") === "help --config") return { code: 0, stdout: Buffer.from("http.curloptResolve\n"), stderr: Buffer.alloc(0) }; if (request.args.includes("ls-remote")) return { code: 0, stdout: Buffer.from(`${COMMIT}\tHEAD\n`), stderr: Buffer.alloc(0) }; if (request.args.includes("init") || request.args.includes("fetch") || request.args.includes("-e")) return { code: 0, stdout: Buffer.alloc(0), stderr: Buffer.alloc(0) }; if (request.args.includes("ls-tree")) return { code: 0, stdout: Buffer.from(entries.map((entry, index) => `100644 blob ${hashes[index]}\t${entry.path}\0`).join("")), stderr: Buffer.alloc(0) }; if (request.args.includes("--batch")) return { code: 0, stdout: Buffer.concat(entries.map((entry, index) => { const body = Buffer.from(entry.data); return Buffer.concat([Buffer.from(`${hashes[index]} blob ${body.length}\n`), body, Buffer.from("\n")]); })), stderr: Buffer.alloc(0) }; return { code: 1, stdout: Buffer.alloc(0), stderr: Buffer.alloc(0) }; }; }
async function npmArchive(): Promise<Buffer> { const pack = tar.pack(); const chunks: Buffer[] = []; pack.on("data", (chunk: Buffer) => chunks.push(Buffer.from(chunk))); const ended = new Promise<void>((resolve, reject) => { pack.once("end", resolve); pack.once("error", reject); }); for (const [name, body, type] of [["package/", "", "directory"], ["package/.claude-plugin/", "", "directory"], ["package/.claude-plugin/plugin.json", JSON.stringify({ name: "tool", version: "1.0.0" }), "file"], ["package/commands/", "", "directory"], ["package/commands/run.md", "run", "file"], ["package/package.json", JSON.stringify({ name: "safe-plugin", version: "1.0.0" }), "file"]] as const) { const bytes = Buffer.from(body); pack.entry({ name, type, size: type === "file" ? bytes.length : 0 }, bytes); } pack.finalize(); await ended; return gzipSync(Buffer.concat(chunks)); }

async function fixture() {
  const home = fs.realpathSync.native(fs.mkdtempSync(path.join(os.tmpdir(), "picc-plugin-service-"))); roots.push(home);
  const profile = path.join(home, ".claude"); const project = path.join(home, "project"); fs.mkdirSync(profile); fs.mkdirSync(path.join(project, ".git"), { recursive: true }); fs.mkdirSync(path.join(project, ".claude"));
  const locations = createLifecycleLocations({ homeDir: home, profilePath: profile, platform: process.platform === "win32" ? "win32" : "posix", project: { activeCheckoutPath: project, checkoutFamilyPath: project } }); if (!locations.ok) throw new Error(locations.error.message);
  const established = await establishOwnedStateStore(locations.value, home); if (!established.ok) throw new Error(established.message);
  const catalogBytes = Buffer.from(JSON.stringify({ name: "official", owner: { name: "Example" }, plugins: [{ name: "other", source: { source: "archive", url: "https://archive.example.org/tool.zip" } }, { name: "tool", source: { source: "archive", url: "https://archive.example.org/tool.zip" } }] })); const catalogDigest = digest(catalogBytes); const source = { kind: "https-catalog", url: "https://catalog.example.org/catalog.json" } as const;
  const snapshotId = `marketplace-${createHash("sha256").update(`${catalogDigest}\0${source.url}`).digest("base64url")}` as const;
  const executableCatalog = deriveExecutableMarketplaceCatalogProjection(catalogBytes, source.kind); if (executableCatalog === undefined) throw new Error("fixture projection"); const target = { authorityKind: "catalog-only", marketplaceName: "official", snapshotId, source, catalogDigest, executableCatalog, provenance: { adapter: "public-https-catalog", canonicalUrl: source.url } } as const;
  const grant = createMarketplaceSnapshotTrustGrant(target); if (!grant.ok) throw new Error(grant.message);
  const raw: OwnedMarketplaceSnapshotRecord = { ownership: "picc-owned", profileKey: established.value.profileKey as `profile-${string}`, ...target, trust: grant.value };
  const snapshotCodec = createOwnedMarketplaceSnapshotCodec({ profileKey: established.value.profileKey as `profile-${string}`, artifactsRoot: established.value.artifactsRoot }); const envelope = createRecordEnvelope(snapshotCodec, "picc-owned", ownedMarketplaceSnapshotScopeKey(raw), raw); if (!envelope.ok) throw new Error(envelope.message);
  const partition = ownedRecordPartition(established.value, "picc-owned", ownedMarketplaceSnapshotScopeKey(raw)); if (!partition.ok) throw new Error(partition.message); fs.mkdirSync(partition.value, { recursive: true }); fs.writeFileSync(path.join(partition.value, "snapshot.json"), envelope.value.bytes);
  const registry = createProducerCodecRegistry([snapshotCodec]); if (!registry.ok) throw new Error(registry.message); const snapshot = readOwnedAdmissionRecords(established.value, registry.value, undefined).marketplaceSnapshots[0]!;
  const registration = { ownership: "picc-owned", name: "official", profileKey: established.value.profileKey as `profile-${string}`, scope: "user", source, selectedSnapshotId: snapshotId } as const;
  return { home, profile, project, store: established.value, checkoutFamilyKey: locations.value.checkoutFamilyKey, registration, snapshot, catalog: { marketplaceName: "official", snapshotId, catalogDigest, registration, snapshot }, source: { kind: "https-zip", url: "https://archive.example.org/tool.zip" } as const };
}

async function relativeCatalog(value: Awaited<ReturnType<typeof fixture>>) {
  const catalogBytes = Buffer.from(JSON.stringify({ name: "official", metadata: { pluginRoot: "plugins" }, plugins: [{ name: "tool", source: "./tool" }] })); const manifest = Buffer.from(JSON.stringify({ name: "tool", version: "1.0.0" })); const command = Buffer.from("run"); const treeDigest = digestArtifactEntries([{ path: ".claude-plugin", kind: "directory" }, { path: ".claude-plugin/marketplace.json", kind: "file", data: catalogBytes }, { path: "plugins", kind: "directory" }, { path: "plugins/tool", kind: "directory" }, { path: "plugins/tool/.claude-plugin", kind: "directory" }, { path: "plugins/tool/.claude-plugin/plugin.json", kind: "file", data: manifest }, { path: "plugins/tool/commands", kind: "directory" }, { path: "plugins/tool/commands/run.md", kind: "file", data: command }]); const artifactRoot = path.join(value.store.artifactsRoot, treeDigest.slice(7)); fs.mkdirSync(path.join(artifactRoot, ".claude-plugin"), { recursive: true }); fs.mkdirSync(path.join(artifactRoot, "plugins", "tool", ".claude-plugin"), { recursive: true }); fs.mkdirSync(path.join(artifactRoot, "plugins", "tool", "commands"), { recursive: true }); fs.writeFileSync(path.join(artifactRoot, ".claude-plugin", "marketplace.json"), catalogBytes); fs.writeFileSync(path.join(artifactRoot, "plugins", "tool", ".claude-plugin", "plugin.json"), manifest); fs.writeFileSync(path.join(artifactRoot, "plugins", "tool", "commands", "run.md"), command);
  const catalogDigest = digest(catalogBytes); const snapshotId = `marketplace-${createHash("sha256").update(`${catalogDigest}\0${treeDigest}`).digest("base64url")}` as const; const marketplaceSource = { kind: "local-directory", path: path.join(value.home, "retired-marketplace-source") } as const; const executableCatalog = deriveExecutableMarketplaceCatalogProjection(catalogBytes, marketplaceSource.kind); if (executableCatalog === undefined) throw new Error("relative fixture projection"); const target: MarketplaceSnapshotTrustTarget = { authorityKind: "materialized", marketplaceName: "official", snapshotId, source: marketplaceSource, catalogDigest, executableCatalog, artifactDigest: treeDigest, treeDigest, rootDigest: treeDigest, selectedRoot: { requested: "tree-root", path: "", usedSingleWrapper: false }, artifactRoot, installRoot: artifactRoot, catalogRelativePath: ".claude-plugin/marketplace.json", provenance: { adapter: "local-directory-snapshot", artifactDigest: treeDigest } }; const grant = createMarketplaceSnapshotTrustGrant(target); if (!grant.ok) throw new Error(grant.message); const record: OwnedMarketplaceSnapshotRecord = { ownership: "picc-owned", profileKey: value.store.profileKey as `profile-${string}`, ...target, trust: grant.value }; const codec = createOwnedMarketplaceSnapshotCodec({ profileKey: value.store.profileKey as `profile-${string}`, artifactsRoot: value.store.artifactsRoot }); const envelope = createRecordEnvelope(codec, "picc-owned", ownedMarketplaceSnapshotScopeKey(record), record); if (!envelope.ok) throw new Error(envelope.message); const partition = ownedRecordPartition(value.store, "picc-owned", ownedMarketplaceSnapshotScopeKey(record)); if (!partition.ok) throw new Error(partition.message); fs.mkdirSync(partition.value, { recursive: true }); fs.writeFileSync(path.join(partition.value, "relative.json"), envelope.value.bytes); const registry = createProducerCodecRegistry([codec]); if (!registry.ok) throw new Error(registry.message); const admitted = readOwnedAdmissionRecords(value.store, registry.value, undefined).marketplaceSnapshots.find((item) => item.snapshotId === snapshotId); if (admitted === undefined) throw new Error("Relative snapshot was not admitted"); const source = { kind: "relative", path: "tool", pluginRoot: "plugins" } as const; const registration = { ...value.registration, source: marketplaceSource, selectedSnapshotId: snapshotId }; return { registration, snapshot: admitted, source, catalog: { marketplaceName: "official", snapshotId, catalogDigest, registration, snapshot: admitted } };
}

async function refreshedSnapshot(value: Awaited<ReturnType<typeof fixture>>, token: string, defaultEnabled?: boolean, dependencies?: readonly string[]): Promise<OwnedMarketplaceSnapshotRecord> {
  const catalogBytes = Buffer.from(JSON.stringify({ name: "official", owner: { name: "Example" }, plugins: [{ name: "tool", source: { source: "archive", url: value.source.url }, ...(defaultEnabled === undefined ? {} : { defaultEnabled }), ...(dependencies === undefined ? {} : { dependencies }) }], revision: token })); const catalogDigest = digest(catalogBytes); const snapshotId = `marketplace-${createHash("sha256").update(`${catalogDigest}\0https://catalog.example.org/catalog.json`).digest("base64url")}` as const; const source = { kind: "https-catalog", url: "https://catalog.example.org/catalog.json" } as const; const executableCatalog = deriveExecutableMarketplaceCatalogProjection(catalogBytes, source.kind); if (executableCatalog === undefined) throw new Error("refresh fixture projection"); const target = { authorityKind: "catalog-only", marketplaceName: "official", snapshotId, source, catalogDigest, executableCatalog, provenance: { adapter: "public-https-catalog", canonicalUrl: source.url } } as const; const grant = createMarketplaceSnapshotTrustGrant(target); if (!grant.ok) throw new Error(grant.message); const raw: OwnedMarketplaceSnapshotRecord = { ownership: "picc-owned", profileKey: value.store.profileKey as `profile-${string}`, ...target, trust: grant.value }; const codec = createOwnedMarketplaceSnapshotCodec({ profileKey: value.store.profileKey as `profile-${string}`, artifactsRoot: value.store.artifactsRoot }); const envelope = createRecordEnvelope(codec, "picc-owned", ownedMarketplaceSnapshotScopeKey(raw), raw); if (!envelope.ok) throw new Error(envelope.message); const partition = ownedRecordPartition(value.store, "picc-owned", ownedMarketplaceSnapshotScopeKey(raw)); if (!partition.ok) throw new Error(partition.message); fs.mkdirSync(partition.value, { recursive: true }); fs.writeFileSync(path.join(partition.value, `snapshot-${token}.json`), envelope.value.bytes); const registry = createProducerCodecRegistry([codec]); if (!registry.ok) throw new Error(registry.message); return readOwnedAdmissionRecords(value.store, registry.value, undefined).marketplaceSnapshots.find((item) => item.snapshotId === snapshotId)!;
}

function catalogSnapshotForSource(value: Awaited<ReturnType<typeof fixture>>, source: import("../src/plugin-lifecycle/types.js").CatalogPluginSource) { const { trust: _trust, ...base } = value.snapshot; const target = { ...base, executableCatalog: { marketplaceName: "official", allowedCrossMarketplaceDependencies: [], declarations: [{ pluginId: "tool@official" as const, source, dependencies: [], dependencyDeclaration: "absent" as const }] } }; const grant = createMarketplaceSnapshotTrustGrant(target); if (!grant.ok) throw new Error(grant.message); const snapshot: OwnedMarketplaceSnapshotRecord = { ...target, trust: grant.value }; const registration = { ...value.registration, selectedSnapshotId: snapshot.snapshotId }; return { snapshot, registration, catalog: { marketplaceName: "official", snapshotId: snapshot.snapshotId, catalogDigest: snapshot.catalogDigest, registration, snapshot } }; }

function build(value: Awaited<ReturnType<typeof fixture>>, state: { snapshot: PluginLocalSnapshot }, id = "plugin_operation", transactionFaults?: import("../src/plugin-lifecycle/transaction.js").TransactionFaultSeam, inspection: Partial<PluginInspection> = {}, checkoutFamilyKey = value.checkoutFamilyKey, acquireOverride?: ConstructorParameters<typeof PluginLifecycleService>[0]["acquire"], injectedInspection: Partial<PluginInspection> = {}) {
  const acquire = vi.fn(async (request: Parameters<ConstructorParameters<typeof PluginLifecycleService>[0]["acquire"]>[0]) => {
    if (acquireOverride !== undefined) return acquireOverride(request); const archive = pluginZip(inspection, request.pluginId.slice(0, request.pluginId.lastIndexOf("@"))); const result = await acquireHttpsZipPlugin(request.source, { store: value.store, resolver: async () => [{ address: "93.184.216.34", family: 4 }], connector: async () => ({ status: 200, headers: {}, body: archive }) });
    return result.ok ? { ok: true as const, value: result.value } : { ok: false as const, code: result.error.code, message: result.error.message };
  });
  const service = new PluginLifecycleService({ store: value.store, profilePath: value.profile, checkoutFamilyKey, observe: () => ({ ...state.snapshot, marketplaceRegistrations: state.snapshot.marketplaceRegistrations ?? [value.registration] }), acquire, operationId: () => id, ...(transactionFaults === undefined ? {} : { transactionFaults }),
    inspect: async (evidence, selection) => { const canonical = await inspectAcquiredPlugin(evidence, selection); return canonical.ok ? { ok: true, value: { ...canonical.value, ...injectedInspection } } : canonical; },
    planSettings: ({ pluginId, scope, value: enabled, declarationOnly }) => Promise.resolve(planPluginSettingsWrite({ homeDir: value.home, profilePath: value.profile, platform: process.platform === "win32" ? "win32" : "posix", project: { activeCheckoutPath: value.project, checkoutFamilyPath: value.project }, projectRoot: value.project, cwd: value.project, managedPaths: [], scope, mutation: { kind: "enabled-plugin", key: pluginId, ...(enabled === undefined ? {} : { value: enabled }) }, declarationOnly })),
  });
  return { service, acquire };
}

function selections(value: Awaited<ReturnType<typeof fixture>>, pluginIds: readonly import("../src/plugin-lifecycle/types.js").QualifiedPluginIdentity[] = ["tool@official"]) { return pluginIds.map((pluginId) => ({ pluginId, registration: value.registration, snapshotId: value.catalog.snapshotId, catalogDigest: value.catalog.catalogDigest, source: value.source, allowedCrossMarketplaceDependencies: [], dependencies: [], dependencyDeclaration: "absent" as const })); }
function reload(value: Awaited<ReturnType<typeof fixture>>, snapshots: readonly OwnedMarketplaceSnapshotRecord[] = [value.snapshot]): PluginLocalSnapshot {
  const preliminary = pluginLifecycleProducerRegistry(value.store, snapshots); if (!preliminary.ok) throw new Error(preliminary.message);
  const generation = observeExecutableGenerationFile(path.join(value.store.generationsRoot, "current.json"), createExecutableAdmissionGenerationCodec(value.store.profileKey as `profile-${string}`));
  const loaded = readOwnedAdmissionRecords(value.store, preliminary.value, generation.status === "valid" ? generation.generation : undefined);
  const rows: PluginObservation[] = loaded.installations.map((authority) => ({ pluginId: authority.record.pluginId, owner: "picc-owned", scope: authority.record.scope, version: authority.record.version, enabled: true, explicitEnabled: true, sourceKind: authority.record.source.kind, trusted: true, dependencies: [], dependencyDeclaration: "complete", authority }));
  return { rows, completeReference: loaded.completeReference, marketplaceRegistrations: [{ ...value.registration, selectedSnapshotId: snapshots[0]?.snapshotId ?? value.registration.selectedSnapshotId }], marketplaceSnapshots: loaded.marketplaceSnapshots, catalogSelections: selections(value) };
}
function admitCrossScopeIdentity(value: Awaited<ReturnType<typeof fixture>>, base: OwnedPluginInstallationRecord): void {
  if (value.checkoutFamilyKey === undefined) throw new Error("Fixture checkout key is absent"); const generationId = "admission-cross-scope"; const withVersion = (record: OwnedPluginInstallationRecord, version: string): OwnedPluginInstallationRecord => ({ ...record, version, resolvedVersionAuthority: { kind: "manifest-version", version }, trust: { ...record.trust, resolvedVersionAuthority: { kind: "manifest-version", version } } }); const records: readonly OwnedPluginInstallationRecord[] = [{ ...withVersion(base, "1.0.0"), executableGenerationId: generationId }, { ...withVersion(base, "0.9.0"), scope: "project", checkoutFamilyKey: value.checkoutFamilyKey, projectKey: value.checkoutFamilyKey, executableGenerationId: generationId }]; const codec = createOwnedPluginInstallationCodec({ profileKey: value.store.profileKey as `profile-${string}`, artifactsRoot: value.store.artifactsRoot, marketplaceSnapshots: { [value.snapshot.snapshotId]: [value.snapshot] } }); const members = records.map((record) => { const scopeKey = ownedInstallationScopeKey(record); const envelope = createRecordEnvelope(codec, "picc-owned", scopeKey, record); if (!envelope.ok) throw new Error(envelope.message); const partition = ownedRecordPartition(value.store, "picc-owned", scopeKey); if (!partition.ok) throw new Error(partition.message); fs.mkdirSync(partition.value, { recursive: true }); fs.writeFileSync(path.join(partition.value, `plugin-${createHash("sha256").update(record.pluginId).digest("base64url")}.json`), envelope.value.bytes); return { pluginId: record.pluginId, scope: record.scope, ...(record.checkoutFamilyKey === undefined ? {} : { checkoutFamilyKey: record.checkoutFamilyKey }), ...(record.projectKey === undefined ? {} : { projectKey: record.projectKey }), recordDigest: envelope.value.envelope.payloadDigest }; }); const generation = createExecutableAdmissionGenerationCodec(value.store.profileKey as `profile-${string}`).decode({ ownership: "picc-owned", profileKey: value.store.profileKey, generationId, members }); if (!generation.ok) throw new Error(generation.message); const bytes = canonicalJsonBytes(generation.value); if (!bytes.ok) throw new Error(bytes.message); fs.writeFileSync(path.join(value.store.generationsRoot, "current.json"), bytes.value);
}

describe("PluginLifecycleService", () => {
  it("round trips only the canonical stable plugin selector wire format", () => {
    const selector = { pluginId: "tool@official", owner: "picc-owned", scope: "project", profileKey: `profile-${"a".repeat(64)}`, projectKey: `checkout-${"b".repeat(64)}` } as const;
    const encoded = encodePluginStableSelector(selector);
    expect(decodePluginStableSelector(encoded)).toEqual(selector);
    const reordered = Buffer.from(JSON.stringify({ owner: selector.owner, pluginId: selector.pluginId, scope: selector.scope, profileKey: selector.profileKey, projectKey: selector.projectKey }), "utf8").toString("base64url");
    expect(decodePluginStableSelector(reordered)).toBeUndefined();
    expect(decodePluginStableSelector(`${encoded}=`)).toBeUndefined();
  });

  it("derives selections only from exact registration and retained snapshot projection authority", async () => {
    const value = await fixture(); const selected = deriveOwnedPluginCatalogSelections([value.registration], [value.snapshot]); expect(selected).toMatchObject({ ok: true, value: [{ pluginId: "other@official" }, { pluginId: "tool@official", source: value.source, allowedCrossMarketplaceDependencies: [], dependencies: [], dependencyDeclaration: "absent" }] });
    expect(deriveOwnedPluginCatalogSelections([{ ...value.registration, selectedSnapshotId: "marketplace-stale" }], [value.snapshot])).toMatchObject({ ok: false, code: "catalog-authority-ambiguous" });
    expect(deriveOwnedPluginCatalogSelections([{ ...value.registration, source: { kind: "https-catalog", url: "https://foreign.example.org/catalog.json" } }], [value.snapshot])).toMatchObject({ ok: false });
    expect(deriveOwnedPluginCatalogSelections([value.registration, value.registration], [value.snapshot])).toMatchObject({ ok: false, code: "catalog-selection-duplicate" }); expect(deriveOwnedPluginCatalogSelections([value.registration], [value.snapshot, value.snapshot])).toMatchObject({ ok: false, code: "catalog-authority-ambiguous" });
    const refreshed = await refreshedSnapshot(value, "selection-refresh", false); const replacement = deriveOwnedPluginCatalogSelections([{ ...value.registration, selectedSnapshotId: refreshed.snapshotId }], [value.snapshot, refreshed]); expect(replacement).toMatchObject({ ok: true, value: [{ pluginId: "tool@official", snapshotId: refreshed.snapshotId, defaultEnabled: false }] });
  });

  it("inspects manifestless and explicit-manifest acquisitions with runtime-canonical projection authority", async () => {
    const value = await fixture(); const manifestless = zip([{ name: ".claude-plugin/" }, { name: "commands/" }, { name: "commands/run.md", data: "run" }]); const acquired = await acquireHttpsZipPlugin(value.source, { store: value.store, resolver: async () => [{ address: "93.184.216.34", family: 4 }], connector: async () => ({ status: 200, headers: {}, body: manifestless }) }); if (!acquired.ok) throw new Error(acquired.error.message);
    const selection = { pluginId: "tool@official" as const, snapshotId: value.snapshot.snapshotId, catalogDigest: value.snapshot.catalogDigest, source: value.source, release: { kind: "version" as const, value: "2.0.0" }, allowedCrossMarketplaceDependencies: ["partner"], dependencies: [{ name: "base", marketplace: "partner", version: "^1", itemIndex: 0 }], dependencyDeclaration: "complete" as const };
    const inspected = await inspectAcquiredPlugin(acquired.value, selection); const emptyProjection = projectPluginManifest({}, "acquired plugin manifest").projection; const expectedDigest = executableDigestForProjection(emptyProjection); if (!expectedDigest.ok) throw new Error(expectedDigest.message); expect(expectedDigest.value).toBe(EMPTY_MANIFEST_EXECUTABLE_DIGEST); expect(inspected).toEqual({ ok: true, value: { pluginId: "tool@official", version: "2.0.0", resolvedVersionAuthority: { kind: "catalog-release", release: selection.release }, executableDigest: EMPTY_MANIFEST_EXECUTABLE_DIGEST, dependencies: selection.dependencies, dependencyDeclaration: "complete", executableComponents: [] } });
    const acquireManifest = async (manifest: string) => acquireHttpsZipPlugin(value.source, { store: value.store, resolver: async () => [{ address: "93.184.216.34", family: 4 }], connector: async () => ({ status: 200, headers: {}, body: zip([{ name: ".claude-plugin/" }, { name: ".claude-plugin/plugin.json", data: manifest }]) }) });
    const withManifest = await acquireManifest(JSON.stringify({ name: "tool", version: "1.0.0" })); if (!withManifest.ok) throw new Error(withManifest.error.message); await expect(inspectAcquiredPlugin(withManifest.value, { ...selection, pluginId: "other@official" })).resolves.toMatchObject({ ok: false, code: "identity-mismatch" });
    await expect(inspectAcquiredPlugin(withManifest.value, { ...selection, release: { kind: "version", value: "9.0.0" } })).resolves.toMatchObject({ ok: true, value: { version: "1.0.0", resolvedVersionAuthority: { kind: "manifest-version", version: "1.0.0" } } });
    const wrongVersion = await acquireManifest(JSON.stringify({ name: "tool", version: 7 })); if (!wrongVersion.ok) throw new Error(wrongVersion.error.message); await expect(inspectAcquiredPlugin(wrongVersion.value, selection)).resolves.toMatchObject({ ok: false, code: "inspection-authority-invalid" });
    const malformed = await acquireManifest("{"); if (!malformed.ok) throw new Error(malformed.error.message); await expect(inspectAcquiredPlugin(malformed.value, selection)).resolves.toMatchObject({ ok: false, code: "manifest-invalid" });
    const excessive = await acquireManifest(JSON.stringify({ name: "tool", version: "1.0.0", dependencies: Object.fromEntries(Array.from({ length: 129 }, (_, index) => [`dep-${index}`, "1"])) })); if (!excessive.ok) throw new Error(excessive.error.message); await expect(inspectAcquiredPlugin(excessive.value, selection)).resolves.toMatchObject({ ok: false, code: "inspection-authority-invalid" });
    const displayOnly = await acquireManifest(JSON.stringify({ name: "tool", version: "1.0.0", description: { malformed: true } })); if (!displayOnly.ok) throw new Error(displayOnly.error.message); await expect(inspectAcquiredPlugin(displayOnly.value, { ...selection, release: undefined })).resolves.toMatchObject({ ok: true, value: { resolvedVersionAuthority: { kind: "manifest-version", version: "1.0.0" } } });
  });

  it.each([
    ["manifest default", { manifestDefaultEnabled: false }],
    ["executable digest", { executableDigest: digest(Buffer.from("forged executable semantics")) }],
    ["dependency declaration", { dependencies: [{ name: "forged", itemIndex: 0 }], dependencyDeclaration: "complete" as const }],
  ] as const)("rejects injected %s semantics that disagree with canonical acquired-tree inspection", async (_field, injectedInspection) => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceRegistrations: [value.registration], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot };
    const built = build(value, state, `plugin_injected_${_field.replaceAll(" ", "_")}`, undefined, {}, value.checkoutFamilyKey, undefined, injectedInspection);
    await expect(built.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog })).resolves.toMatchObject({ ok: false, code: "inspection-authority-conflict" });
    expect(fs.existsSync(path.join(value.profile, "settings.json"))).toBe(false);
  });

  it("commits and freshly admits a manifestless ZIP without catalog release through exact digest fallback", async () => {
    const value = await fixture(); const archive = zip([{ name: ".claude-plugin/" }, { name: "commands/" }, { name: "commands/run.md", data: "run" }]); const acquired = await acquireHttpsZipPlugin(value.source, { store: value.store, resolver: async () => [{ address: "93.184.216.34", family: 4 }], connector: async () => ({ status: 200, headers: {}, body: archive }) }); if (!acquired.ok) throw new Error(acquired.error.message); const authority = { kind: "zip-artifact-digest" as const, digest: acquired.value.artifactDigest }; const state = { snapshot: { rows: [], marketplaceRegistrations: [value.registration], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const built = build(value, state, "plugin_manifestless_zip", undefined, { version: `zip-${acquired.value.artifactDigest.slice(7)}`, resolvedVersionAuthority: authority, executableDigest: EMPTY_MANIFEST_EXECUTABLE_DIGEST, dependencyDeclaration: "absent", executableComponents: [] }, value.checkoutFamilyKey, async () => ({ ok: true, value: acquired.value })); const preview = await built.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!preview.ok) throw new Error(preview.message); expect(await built.service.execute(preview.value, preview.value.confirmationDigest)).toMatchObject({ ok: true }); const fresh = reload(value); expect(fresh.rows[0]?.authority?.record).toMatchObject({ version: `zip-${acquired.value.artifactDigest.slice(7)}`, resolvedVersionAuthority: authority, trust: { resolvedVersionAuthority: authority } });
  });

  it("keeps a real service-installed catalog-dependent inert on genuinely fresh project assembly when its dependency is missing", async () => {
    const value = await fixture();
    const snapshot = await refreshedSnapshot(value, "catalog-dependency", false, ["missing"]);
    const registration = { ...value.registration, selectedSnapshotId: snapshot.snapshotId };
    const derived = deriveOwnedPluginCatalogSelections([registration], [snapshot]); if (!derived.ok) throw new Error(derived.message);
    const selection = derived.value.find((item) => item.pluginId === "tool@official"); if (selection === undefined) throw new Error("Missing retained tool selection");
    const catalog = { marketplaceName: "official", snapshotId: snapshot.snapshotId, catalogDigest: snapshot.catalogDigest, registration, snapshot, defaultEnabled: selection.defaultEnabled, allowedCrossMarketplaceDependencies: selection.allowedCrossMarketplaceDependencies };
    const state = { snapshot: { rows: [], marketplaceRegistrations: [registration], marketplaceSnapshots: [snapshot], catalogSelections: [selection] } as PluginLocalSnapshot };
    const service = build(value, state, "plugin_catalog_dependency_fresh").service;
    const preview = await service.install({ pluginId: "tool@official", source: value.source, catalog }); if (!preview.ok) throw new Error(preview.message);
    expect(preview.value.dependencies.graph.find((item) => item.pluginId === "tool@official")).toMatchObject({ dependencies: [{ name: "missing", itemIndex: 0 }] });
    expect(await service.execute(preview.value, preview.value.confirmationDigest)).toMatchObject({ ok: true, value: { outcome: "committed" } });
    const settingsPath = path.join(value.profile, "settings.json"); const settings = JSON.parse(fs.readFileSync(settingsPath, "utf8")); settings.enabledPlugins["tool@official"] = true; fs.writeFileSync(settingsPath, JSON.stringify(settings));
    const project = loadClaudeProject({ cwd: value.project, userDir: value.profile, homeDir: value.home, managedSettingsPaths: [], managedArtifactDirs: [] });
    expect(project.pluginAdmissions).toContainEqual(expect.objectContaining({ ownership: "picc-owned", pluginId: "tool@official", catalogDependencies: [{ name: "missing", itemIndex: 0 }] }));
    expect(project.plugins.map((plugin) => plugin.pluginId)).not.toContain("tool@official");
    expect(project.pluginContexts.has("tool@official")).toBe(false);
    expect(project.pluginResolutionOutcomes.find((outcome) => outcome.pluginId === "tool@official")).toMatchObject({ status: "rejected", diagnostics: [expect.objectContaining({ message: expect.stringContaining("missing") })] });
  });

  it("ignores ambient catalog mutations when exact retained selection authority remains unchanged", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceRegistrations: [value.registration], marketplaceSnapshots: [value.snapshot], catalogSelections: [{ pluginId: "tool@foreign" as const, snapshotId: value.snapshot.snapshotId, catalogDigest: value.snapshot.catalogDigest, source: { kind: "npm" as const, package: "attacker", registry: "https://registry.npmjs.org" } }] } as PluginLocalSnapshot }; const service = build(value, state, "plugin_ambient_inert").service; const preview = await service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); expect(preview).toMatchObject({ ok: true, value: { requestedSource: value.source } }); if (preview.ok) await service.discardPreview(preview.value.operationId);
  });

  it("builds validated install previews from authentic relative, Git, and npm source-refined evidence", async () => {
    for (const family of ["relative", "Git", "npm"] as const) {
      const value = await fixture(); let source: import("../src/plugin-lifecycle/types.js").CatalogPluginSource; let catalog: import("../src/plugin-lifecycle/plugin-service.js").PluginCatalogAuthority; let acquire: ConstructorParameters<typeof PluginLifecycleService>[0]["acquire"]; let expectedKind: "marketplace-relative" | "git" | "npm"; let expectedRevision: string; let registration: OwnedMarketplaceRecord | undefined;
      if (family === "relative") { const relative = await relativeCatalog(value); source = relative.source; catalog = relative.catalog; registration = relative.registration; expectedKind = "marketplace-relative"; expectedRevision = relative.snapshot.snapshotId; acquire = createPluginAcquisitionAdapter({ store: value.store, snapshots: () => [relative.snapshot] }); }
      else if (family === "Git") { source = { kind: "github", repository: "owner/repository", sha: COMMIT }; catalog = { ...value.catalog, snapshot: value.snapshot }; expectedKind = "git"; expectedRevision = COMMIT; acquire = createPluginAcquisitionAdapter({ store: value.store, snapshots: () => [value.snapshot], git: { resolver: async () => [{ address: "8.8.8.8", family: 4 }], runner: successfulGitRunner() } }); }
      else { const archive = await npmArchive(); const integrity = `sha512-${createHash("sha512").update(archive).digest("base64")}`; const metadata = Buffer.from(JSON.stringify({ name: "safe-plugin", "dist-tags": { latest: "1.0.0" }, versions: { "1.0.0": { name: "safe-plugin", version: "1.0.0", dist: { tarball: "https://registry.npmjs.org/safe-plugin/-/safe-plugin-1.0.0.tgz", integrity } } } })); source = { kind: "npm", package: "safe-plugin", version: "1.0.0", registry: "https://registry.npmjs.org" }; catalog = { ...value.catalog, snapshot: value.snapshot }; expectedKind = "npm"; expectedRevision = "1.0.0"; acquire = createPluginAcquisitionAdapter({ store: value.store, snapshots: () => [value.snapshot], npm: { resolver: async () => [{ address: "8.8.8.8", family: 4 }], connector: async ({ url }) => ({ status: 200, headers: {}, body: url.pathname.endsWith(".tgz") ? archive : metadata }) } }); }
      const selectedAuthority = family === "relative" ? { snapshot: catalog.snapshot!, registration: registration!, catalog } : catalogSnapshotForSource(value, source); if (family !== "relative") catalog = selectedAuthority.catalog; const selection = { pluginId: "tool@official" as const, snapshotId: catalog.snapshotId, catalogDigest: catalog.catalogDigest, source, allowedCrossMarketplaceDependencies: [], dependencies: [], dependencyDeclaration: "absent" as const }; const state = { snapshot: { rows: [], marketplaceRegistrations: [selectedAuthority.registration], marketplaceSnapshots: [selectedAuthority.snapshot], catalogSelections: [selection] } as PluginLocalSnapshot }; const service = build(value, state, `plugin_source_${family}`, undefined, {}, value.checkoutFamilyKey, acquire).service; const preview = await service.install({ pluginId: "tool@official", source, catalog }); if (!preview.ok) throw new Error(`${family}:${preview.code}:${preview.message}`); expect(preview).toMatchObject({ ok: true, value: { requestedSource: source, source: { kind: expectedKind }, immutableRevision: expectedRevision, artifactDigest: expect.stringMatching(/^sha256:/), rootDigest: expect.stringMatching(/^sha256:/), executableDigest: expect.stringMatching(/^sha256:/), trust: { target: "tool@official", rootDigest: expect.stringMatching(/^sha256:/), executableDigest: expect.stringMatching(/^sha256:/) } } }); const model = projectPluginPreviewForModel(preview.value); expect(model.selectedSource).toEqual(source); expect(model.sourceKind).toBe(expectedKind); expect(model.trust).toMatchObject({ target: "tool@official", rootDigest: preview.value.rootDigest, executableDigest: preview.value.executableDigest }); if (family === "npm") { expect(preview.value.source).toMatchObject({ kind: "npm", package: "safe-plugin", version: "1.0.0", integrity: expect.stringMatching(/^sha512-/) }); expect(preview.value.trust?.selectedRoot).toEqual({ requested: "package/", path: "", usedSingleWrapper: true }); } await service.discardPreview(preview.value.operationId);
    }
  }, 30_000);

  it("keeps list/details path-safe and refuses imported/managed mutation before acquisition", async () => {
    const value = await fixture(); const imported: PluginObservation = { pluginId: "tool@official", owner: "claude-imported-readonly", scope: "user", version: "1.0.0", enabled: true, trusted: false, guidance: "Use Claude Code" };
    const state = { snapshot: { rows: [imported], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } }; const { service, acquire } = build(value, state);
    expect(service.list()).toEqual([expect.objectContaining({ pluginId: "tool@official", owner: "claude-imported-readonly", guidance: "This plugin is Claude-owned; use Claude Code to change it." })]); expect(JSON.stringify(service.list())).not.toContain(value.home); expect(service.details("tool@official")).toMatchObject({ ok: true });
    await expect(service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog })).resolves.toMatchObject({ ok: false, code: "ownership-conflict" }); expect(acquire).not.toHaveBeenCalled();
    state.snapshot = { rows: [{ ...imported, owner: "managed", scope: "managed" }], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) }; await expect(service.enable("tool@official")).resolves.toMatchObject({ ok: false, code: "managed-readonly" });
  });

  it("reserves operation ids before acquisition and cancels only never-started evidence", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const built = build(value, state, "plugin_reserved"); const first = await built.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); expect(first.ok).toBe(true); const calls = built.acquire.mock.calls.length; await expect(built.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog })).resolves.toMatchObject({ ok: false, code: "duplicate-operation-id" }); expect(built.acquire).toHaveBeenCalledTimes(calls); if (first.ok) expect(await built.service.discardPreview(first.value.operationId)).toEqual({ ok: true, value: undefined }); expect(fs.readdirSync(value.store.stagingRoot)).toEqual([]);
  });

  it("cleans stale previews and reuses their released reservation", async () => {
    const value = await fixture(); const original = { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot; const state = { snapshot: original }; const built = build(value, state, "plugin_stale_reuse"); const stale = await built.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!stale.ok) throw new Error(stale.message); state.snapshot = { ...original, effectiveEnablement: { "tool@official": false } }; expect(await built.service.execute(stale.value, stale.value.confirmationDigest)).toMatchObject({ ok: false, code: "stale-preview" }); expect(fs.readdirSync(value.store.stagingRoot)).toEqual([]); state.snapshot = original; const reused = await built.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); expect(reused.ok).toBe(true); if (reused.ok) await built.service.discardPreview(reused.value.operationId);
  });

  it("installs through exact ZIP evidence, trust, authentic settings, record, and generation participants", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const { service, acquire } = build(value, state);
    const preview = await service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); expect(acquire).toHaveBeenCalledTimes(1); expect(preview).toMatchObject({ ok: true, value: { action: "install", scope: "user", source: { kind: "zip" }, enablement: { enabled: true, source: "manifest-default" }, trust: { target: "tool@official" }, dependencies: { blocking: false }, participants: [{ kind: "plugin-installation" }, { kind: "plugin-settings" }, { kind: "executable-admission-generation", targetClass: "generation" }] } });
    if (!preview.ok) throw new Error(preview.message); const modelPreview = projectPluginPreviewForModel(preview.value); expect(modelPreview.selectedSource).toEqual(value.source); expect(JSON.stringify(modelPreview)).not.toContain(value.home); expect(JSON.stringify(modelPreview)).not.toContain("snapshotRoot"); expect(modelPreview.settingsEffect).toEqual({ requested: true, effective: true, scope: "user", declarationOnly: false }); expect(await service.execute(preview.value, "wrong")).toMatchObject({ ok: false, code: "confirmation-mismatch" }); const result = await service.execute(preview.value, preview.value.confirmationDigest); expect(result).toMatchObject({ ok: true, value: { outcome: "committed", completed: 3 } }); expect(await service.execute(preview.value, preview.value.confirmationDigest)).toEqual(result); expect(await service.receipt(preview.value.operationId)).toEqual(result);
    expect(JSON.parse(fs.readFileSync(path.join(value.profile, "settings.json"), "utf8")).enabledPlugins["tool@official"]).toBe(true); state.snapshot = reload(value); expect(state.snapshot.completeReference?.installations).toHaveLength(1); expect(state.snapshot.completeReference?.installations[0]!.record.trust.executableDigest).toBe(preview.value.executableDigest);
  });

  it.each([
    ["update", true, false],
    ["reinstall", false, true],
  ] as const)("preserves an explicit declaration without writing it while %s reports the observed effective state", async (action, explicitEnabled, effectiveEnabled) => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const first = build(value, state, `plugin_initial_${action}`); const install = await first.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!install.ok) throw new Error(install.message); expect((await first.service.execute(install.value, install.value.confirmationDigest)).ok).toBe(true); state.snapshot = reload(value); state.snapshot = { ...state.snapshot, rows: state.snapshot.rows.map((row) => ({ ...row, explicitEnabled, enabled: effectiveEnabled })) };
    const next = build(value, state, `plugin_${action}_effective`); const request = { source: value.source, catalog: { ...value.catalog, snapshot: state.snapshot.marketplaceSnapshots[0]! } }; const preview = action === "update" ? await next.service.update("tool@official", request, { record: state.snapshot.rows[0]!.authority }) : await next.service.reinstall("tool@official", request, { record: state.snapshot.rows[0]!.authority }); expect(preview).toMatchObject({ ok: true, value: { action, enablement: { enabled: effectiveEnabled, source: "existing-effective" } } }); if (!preview.ok) throw new Error(preview.message); expect(preview.value.participants.some((item) => item.kind === "plugin-settings")).toBe(false); expect(next.acquire).toHaveBeenCalledTimes(1); await next.service.discardPreview(preview.value.operationId);
  });

  it("derives update enablement from the new catalog when no explicit declaration exists without creating one", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const installing = build(value, state, "plugin_default_install"); const installed = await installing.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!installed.ok) throw new Error(installed.message); expect((await installing.service.execute(installed.value, installed.value.confirmationDigest)).ok).toBe(true); state.snapshot = reload(value); const settingsPath = path.join(value.profile, "settings.json"); const settings = JSON.parse(fs.readFileSync(settingsPath, "utf8")); delete settings.enabledPlugins["tool@official"]; fs.writeFileSync(settingsPath, JSON.stringify(settings)); const refreshed = await refreshedSnapshot(value, "default-off", false); state.snapshot = reload(value, [value.snapshot, refreshed]); state.snapshot = { ...state.snapshot, rows: state.snapshot.rows.map((row) => ({ ...row, enabled: true, explicitEnabled: undefined })), marketplaceRegistrations: [{ ...value.registration, selectedSnapshotId: refreshed.snapshotId }], marketplaceSnapshots: [value.snapshot, refreshed], catalogSelections: selections(value).map((selection) => ({ ...selection, registration: { ...value.registration, selectedSnapshotId: refreshed.snapshotId }, snapshotId: refreshed.snapshotId, catalogDigest: refreshed.catalogDigest, defaultEnabled: false })) };
    const updating = build(value, state, "plugin_default_update"); const preview = await updating.service.update("tool@official", { source: value.source, catalog: { ...value.catalog, registration: { ...value.registration, selectedSnapshotId: refreshed.snapshotId }, snapshotId: refreshed.snapshotId, catalogDigest: refreshed.catalogDigest, defaultEnabled: false, snapshot: refreshed } }, { selector: updating.service.list()[0]!.selector }); if (!preview.ok) throw new Error(`${preview.code}:${preview.message}`); expect(preview).toMatchObject({ ok: true, value: { enablement: { enabled: false, source: "marketplace-default" } } }); expect(preview.value.participants.some((item) => item.kind === "plugin-settings")).toBe(false); expect((await updating.service.execute(preview.value, preview.value.confirmationDigest)).ok).toBe(true); expect(Object.hasOwn(JSON.parse(fs.readFileSync(settingsPath, "utf8")).enabledPlugins, "tool@official")).toBe(false);
  });

  it("does not treat declaration-only disclosure as same-identity mutation authority", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const installing = build(value, state, "plugin_declaration_install"); const installed = await installing.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!installed.ok) throw new Error(installed.message); expect((await installing.service.execute(installed.value, installed.value.confirmationDigest)).ok).toBe(true); state.snapshot = reload(value); const owned = state.snapshot.rows[0]!; state.snapshot = { ...state.snapshot, rows: [...state.snapshot.rows, { pluginId: "tool@official", owner: "claude-imported-readonly", scope: "project", version: "1.0.0", enabled: true, trusted: true }] };
    const disabling = build(value, state, "plugin_declaration_disable").service; await expect(disabling.disable("tool@official", { record: owned.authority, declarationOnly: true })).resolves.toMatchObject({ ok: false, code: "unsafe-identity-wide-setting" }); const removing = build(value, state, "plugin_declaration_remove").service; await expect(removing.uninstall("tool@official", { record: owned.authority, removeDeclaration: true, declarationOnly: true })).resolves.toMatchObject({ ok: false, code: "unsafe-identity-wide-setting" });
  });

  it("blocks unresolved dependencies and disabling an enabled dependency with ordered guidance", async () => {
    const value = await fixture(); const dependency: PluginObservation = { pluginId: "dep@official", owner: "picc-owned", scope: "user", version: "1.0.0", enabled: true, trusted: true, dependencies: [], dependencyDeclaration: "complete", authority: {} as never }; const dependent: PluginObservation = { pluginId: "tool@official", owner: "picc-owned", scope: "user", version: "1.0.0", enabled: true, trusted: true, dependencies: [{ name: "dep", itemIndex: 0 }], dependencyDeclaration: "complete", authority: {} as never }; const state = { snapshot: { rows: [dependency, dependent], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } };
    const { service } = build(value, state); await expect(service.disable("dep@official", { record: dependency.authority })).resolves.toMatchObject({ ok: false, code: "required-dependency", message: expect.stringContaining("tool@official") });
  });

  it("resolves one effective dependency candidate and overlays the exactly selected update candidate", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const installing = build(value, state, "plugin_dependency_base"); const installed = await installing.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!installed.ok) throw new Error(installed.message); expect((await installing.service.execute(installed.value, installed.value.confirmationDigest)).ok).toBe(true); state.snapshot = reload(value);
    const selected = state.snapshot.rows[0]!; const importedSameIdentity: PluginObservation = { pluginId: "tool@official", owner: "claude-imported-readonly", scope: "project", version: "0.9.0", enabled: true, trusted: true, dependencies: [], dependencyDeclaration: "complete" }; const userDependency: PluginObservation = { pluginId: "dep@official", owner: "claude-imported-readonly", scope: "user", version: "1.0.0", enabled: false, trusted: true, dependencies: [], dependencyDeclaration: "complete" }; const projectDependency: PluginObservation = { ...userDependency, scope: "project", version: "2.0.0", enabled: true }; state.snapshot = { ...state.snapshot, rows: [selected, importedSameIdentity, userDependency, projectDependency] };
    const updating = build(value, state, "plugin_dependency_effective", undefined, { dependencies: [{ name: "dep", version: "^2", itemIndex: 0 }] }); const preview = await updating.service.update("tool@official", { source: value.source, catalog: { ...value.catalog, snapshot: state.snapshot.marketplaceSnapshots[0]! } }, { record: selected.authority }); expect(preview).toMatchObject({ ok: true, value: { dependencies: { blocking: false, graph: expect.arrayContaining([expect.objectContaining({ pluginId: "dep@official", version: "2.0.0", enabled: true })]) } } }); if (preview.ok) await updating.service.discardPreview(preview.value.operationId);
  });

  it("updates one exact authority when authentic same-identity predecessors differ across scopes", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const installing = build(value, state, "plugin_cross_scope_base"); const installed = await installing.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!installed.ok) throw new Error(installed.message); expect((await installing.service.execute(installed.value, installed.value.confirmationDigest)).ok).toBe(true); const base = reload(value).rows[0]!.authority!.record; admitCrossScopeIdentity(value, base); state.snapshot = reload(value); expect(state.snapshot.rows.map((row) => [row.scope, row.version]).sort()).toEqual([["project", "0.9.0"], ["user", "1.0.0"]]);
    const selected = state.snapshot.rows.find((row) => row.scope === "user")!.authority!; const updating = build(value, state, "plugin_cross_scope_update", undefined, { version: "2.0.0" }); const preview = await updating.service.update("tool@official", { source: value.source, catalog: { ...value.catalog, snapshot: state.snapshot.marketplaceSnapshots[0]! } }, { record: selected }); expect(preview).toMatchObject({ ok: true, value: { action: "update", dependencies: { blocking: false, graph: [expect.objectContaining({ pluginId: "tool@official", version: "2.0.0", ownership: "picc-owned" })] } } }); if (!preview.ok) throw new Error(preview.message); expect(await updating.service.execute(preview.value, preview.value.confirmationDigest)).toMatchObject({ ok: true, value: { outcome: "committed" } }); const loaded = reload(value); expect(loaded.rows.map((row) => [row.scope, row.version]).sort()).toEqual([["project", "0.9.0"], ["user", "2.0.0"]]);
  });

  it("fails dependency posture indeterminate for conflicting same-precedence observations", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const installing = build(value, state, "plugin_dependency_conflict_base"); const installed = await installing.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!installed.ok) throw new Error(installed.message); expect((await installing.service.execute(installed.value, installed.value.confirmationDigest)).ok).toBe(true); state.snapshot = reload(value); const dependency = (version: string): PluginObservation => ({ pluginId: "dep@official", owner: "claude-imported-readonly", scope: "project", version, enabled: true, trusted: true, dependencies: [], dependencyDeclaration: "complete" }); state.snapshot = { ...state.snapshot, rows: [...state.snapshot.rows, dependency("1.0.0"), dependency("2.0.0")] };
    const updating = build(value, state, "plugin_dependency_conflict", undefined, { dependencies: [{ name: "dep", itemIndex: 0 }] }); await expect(updating.service.update("tool@official", { source: value.source, catalog: { ...value.catalog, snapshot: state.snapshot.marketplaceSnapshots[0]! } }, { record: state.snapshot.rows[0]!.authority })).resolves.toMatchObject({ ok: false, code: "dependency-blocked", message: expect.stringContaining("indeterminate") });
  });

  it("enables and disables only authentic settings declarations while loaded code remains unchanged", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const installing = build(value, state, "plugin_for_enablement"); const install = await installing.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!install.ok) throw new Error(install.message); const installed = await installing.service.execute(install.value, install.value.confirmationDigest); if (!installed.ok) throw new Error(installed.message); state.snapshot = reload(value); const generation = state.snapshot.completeReference!.generation.generationId; const selected = state.snapshot.rows[0]!.authority!;
    const disabling = build(value, state, "plugin_disable"); const disabled = await disabling.service.disable("tool@official", { record: selected }); if (!disabled.ok) throw new Error(disabled.message); expect(disabled.value.participants).toEqual([expect.objectContaining({ kind: "plugin-settings", targetClass: "external" })]); expect(await disabling.service.execute(disabled.value, disabled.value.confirmationDigest)).toMatchObject({ ok: true, value: { outcome: "committed" } }); expect(observeExecutableGenerationFile(path.join(value.store.generationsRoot, "current.json"), createExecutableAdmissionGenerationCodec(value.store.profileKey as `profile-${string}`))).toMatchObject({ status: "valid", generation: { generationId: generation } });
    state.snapshot = { ...state.snapshot, rows: state.snapshot.rows.map((row) => ({ ...row, enabled: false, explicitEnabled: false })) }; const enabling = build(value, state, "plugin_enable"); const enabled = await enabling.service.enable("tool@official", { selector: enabling.service.list()[0]!.selector }); if (!enabled.ok) throw new Error(enabled.message); expect(enabled.value.generationId).toBeUndefined(); expect(await enabling.service.execute(enabled.value, enabled.value.confirmationDigest)).toMatchObject({ ok: true, value: { outcome: "committed" } }); expect(JSON.parse(fs.readFileSync(path.join(value.profile, "settings.json"), "utf8")).enabledPlugins["tool@official"]).toBe(true);
  });

  it("recovers an interrupted safe installation prefix through the trusted plugin codec", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; let interrupted = false; const built = build(value, state, "plugin_recovery", { hit: (phase, index) => { if (!interrupted && phase === "after-replacement" && index === 0) { interrupted = true; throw new Error("interrupt"); } } }); const preview = await built.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!preview.ok) throw new Error(preview.message); expect(await built.service.execute(preview.value, preview.value.confirmationDigest)).toMatchObject({ ok: false, code: "pending-recovery" }); const contender = build(value, state, "plugin_blocked_by_pending"); await expect(contender.service.install({ pluginId: "other@official", source: value.source, catalog: value.catalog })).resolves.toMatchObject({ ok: false, code: "pending-recovery" }); expect(contender.acquire).not.toHaveBeenCalled(); expect(await built.service.recoveryStatus(preview.value.operationId)).toMatchObject({ ok: true, value: { completed: 1, actions: expect.arrayContaining(["complete", "rollback"]) } }); expect(await built.service.recover(preview.value.operationId, "rollback")).toMatchObject({ ok: true, value: { outcome: "rolled-back" } }); expect(fs.existsSync(path.join(value.store.generationsRoot, "current.json"))).toBe(false);
  });

  it("uses fresh trusted service instances to complete interrupted install and roll back survivor/data uninstall", async () => {
    const absentProbe = { observe: async () => ({ state: "absent" as const }) };
    const value = await fixture(); const ids = ["other@official", "tool@official"] as const; const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value, ids) } as PluginLocalSnapshot }; let interrupted = false; const installing = build(value, state, "plugin_fresh_complete", { hit: (phase, index) => { if (!interrupted && phase === "after-replacement" && index === 0) { interrupted = true; throw new Error("interrupt"); } } }).service; const install = await installing.install({ pluginId: "other@official", source: value.source, catalog: value.catalog }); if (!install.ok) throw new Error(install.message); expect(await installing.execute(install.value, install.value.confirmationDigest)).toMatchObject({ ok: false, code: "pending-recovery" }); const freshInstallRecovery = new LifecycleRecoveryService({ store: value.store, snapshots: [value.snapshot], processOwnershipProbe: absentProbe }); expect(await freshInstallRecovery.recover(install.value.operationId, "complete")).toMatchObject({ ok: true, value: { outcome: "committed" } }); state.snapshot = { ...reload(value), catalogSelections: selections(value, ids) };
    const second = build(value, state, "plugin_fresh_second").service; const secondPreview = await second.install({ pluginId: "tool@official", source: value.source, catalog: { ...value.catalog, snapshot: state.snapshot.marketplaceSnapshots[0]! } }); if (!secondPreview.ok) throw new Error(secondPreview.message); expect((await second.execute(secondPreview.value, secondPreview.value.confirmationDigest)).ok).toBe(true); state.snapshot = { ...reload(value), catalogSelections: selections(value, ids) }; const dataPath = path.join(value.store.dataRoot, `plugin-${createHash("sha256").update("tool@official").digest("base64url")}`); fs.mkdirSync(dataPath); fs.writeFileSync(path.join(dataPath, "state.bin"), "restore"); let removeInterrupted = false; const removing = build(value, state, "plugin_fresh_rollback", { hit: (phase, index) => { if (!removeInterrupted && phase === "after-data-retirement-rename" && index === 2) { removeInterrupted = true; throw new Error("interrupt"); } } }).service; const selected = state.snapshot.rows.find((row) => row.pluginId === "tool@official")!.authority!; const remove = await removing.uninstall("tool@official", { record: selected, removeData: true }); if (!remove.ok) throw new Error(remove.message); expect(await removing.execute(remove.value, remove.value.confirmationDigest)).toMatchObject({ ok: false, code: "pending-recovery" }); const freshRemoveRecovery = new LifecycleRecoveryService({ store: value.store, snapshots: [value.snapshot], processOwnershipProbe: absentProbe }); expect(await freshRemoveRecovery.recover(remove.value.operationId, "rollback")).toMatchObject({ ok: true, value: { outcome: "rolled-back" } }); expect(fs.existsSync(dataPath)).toBe(true); state.snapshot = { ...reload(value), catalogSelections: selections(value, ids) }; expect(state.snapshot.rows.map((row) => row.pluginId).sort()).toEqual([...ids].sort());
  }, 30_000);

  it("rejects uninstall when its current selected predecessor disagrees with the dependency graph", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const installing = build(value, state, "plugin_uninstall_graph_base").service; const installed = await installing.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!installed.ok) throw new Error(installed.message); expect((await installing.execute(installed.value, installed.value.confirmationDigest)).ok).toBe(true); state.snapshot = reload(value); let interrupted = false; const removing = build(value, state, "plugin_uninstall_graph", { hit: (phase, index) => { if (!interrupted && phase === "after-forward-deletion" && index === 0) { interrupted = true; throw new Error("interrupt"); } } }).service; const preview = await removing.uninstall("tool@official", { record: state.snapshot.rows[0]!.authority }); if (!preview.ok) throw new Error(preview.message); expect(await removing.execute(preview.value, preview.value.confirmationDigest)).toMatchObject({ ok: false, code: "pending-recovery" }); const journal = await readTransactionJournal(value.store, preview.value.operationId); if (!journal.ok) throw new Error(journal.message); const registry = pluginLifecycleTransactionRegistry(value.store, [value.snapshot]); if (!registry.ok) throw new Error(registry.message); const codec = registry.value.lookup("plugin-lifecycle", 1)!; const summary = structuredClone(journal.value.confirmationSummary) as Record<string, unknown>; const dependencies = summary["dependencies"] as { graph: Array<{ version: string }> }; dependencies.graph[0]!.version = "9.9.9"; const { confirmationDigest: _ignored, ...unsigned } = summary; const bytes = canonicalJsonBytes(unsigned); if (!bytes.ok) throw new Error(bytes.message); const contradictory = { ...unsigned, confirmationDigest: digest(bytes.value) }; expect(codec.requiredLocks(contradictory, journal.value.participants)).toMatchObject({ ok: false, code: "invalid-plan" }); expect(await removing.recover(preview.value.operationId, "rollback")).toMatchObject({ ok: true, value: { outcome: "rolled-back" } });
  });

  it("executes all four uninstall declaration/data choices with exact survivor-free generation truth", async () => {
    for (const removeDeclaration of [false, true]) for (const removeData of [false, true]) {
      const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot };
      const installing = build(value, state, `plugin_install_${Number(removeDeclaration)}_${Number(removeData)}`); const install = await installing.service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!install.ok) throw new Error(install.message); const installed = await installing.service.execute(install.value, install.value.confirmationDigest); if (!installed.ok) throw new Error(installed.message);
      state.snapshot = reload(value); const selected = state.snapshot.rows[0]!.authority!; const dataPath = path.join(value.store.dataRoot, `plugin-${createHash("sha256").update("tool@official").digest("base64url")}`); fs.mkdirSync(dataPath); fs.writeFileSync(path.join(dataPath, "state.bin"), "preserve-or-retire");
      const removing = build(value, state, `plugin_remove_${Number(removeDeclaration)}_${Number(removeData)}`); const preview = await removing.service.uninstall("tool@official", { record: selected, removeDeclaration, removeData }); expect(preview).toMatchObject({ ok: true, value: { removeDeclaration, removeData } }); if (!preview.ok) throw new Error(preview.message); const result = await removing.service.execute(preview.value, preview.value.confirmationDigest); expect(result).toMatchObject({ ok: true, value: { outcome: "committed" } });
      const settings = JSON.parse(fs.readFileSync(path.join(value.profile, "settings.json"), "utf8")); expect(Object.hasOwn(settings.enabledPlugins ?? {}, "tool@official")).toBe(!removeDeclaration); expect(fs.existsSync(dataPath)).toBe(!removeData); expect(reload(value).completeReference?.installations).toHaveLength(0);
    }
  }, 30_000);

  it("rebinds every predecessor across two-plugin install, update, reinstall, and uninstall generations", async () => {
    const value = await fixture(); const ids = ["other@official", "tool@official"] as const; const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value, ids) } as PluginLocalSnapshot };
    const request = (pluginId: typeof ids[number]) => ({ pluginId, source: value.source, catalog: { ...value.catalog, snapshot: state.snapshot.marketplaceSnapshots[0]! } });
    const otherService = build(value, state, "plugin_other").service; const other = await otherService.install(request("other@official")); if (!other.ok) throw new Error(other.message); expect((await otherService.execute(other.value, other.value.confirmationDigest)).ok).toBe(true);
    state.snapshot = { ...reload(value), catalogSelections: selections(value, ids) }; const installing = build(value, state, "plugin_second").service; const second = await installing.install(request("tool@official")); if (!second.ok) throw new Error(second.message); expect(second.value.participants.map((item) => item.kind)).toEqual(["plugin-installation", "plugin-installation-replace", "plugin-settings", "executable-admission-generation"]); expect((await installing.execute(second.value, second.value.confirmationDigest)).ok).toBe(true);
    state.snapshot = { ...reload(value), catalogSelections: selections(value, ids) }; expect(state.snapshot.completeReference?.installations).toHaveLength(2); const selectTool = () => state.snapshot.rows.find((row) => row.pluginId === "tool@official")!.authority!;
    for (const [action, id] of [["update", "plugin_update_two"], ["reinstall", "plugin_reinstall_two"]] as const) { const service = build(value, state, id).service; const preview = action === "update" ? await service.update("tool@official", { source: value.source, catalog: request("tool@official").catalog }, { selector: service.list().find((row) => row.pluginId === "tool@official")!.selector }) : await service.reinstall("tool@official", { source: value.source, catalog: request("tool@official").catalog }, { record: selectTool() }); if (!preview.ok) throw new Error(preview.message); expect(preview.value.participants.filter((item) => item.kind === "plugin-installation-replace")).toHaveLength(2); expect((await service.execute(preview.value, preview.value.confirmationDigest)).ok).toBe(true); state.snapshot = { ...reload(value), catalogSelections: selections(value, ids) }; expect(new Set(state.snapshot.completeReference!.installations.map((item) => item.record.executableGenerationId))).toEqual(new Set([state.snapshot.completeReference!.generation.generationId])); }
    const removing = build(value, state, "plugin_remove_two").service; const remove = await removing.uninstall("tool@official", { record: selectTool() }); if (!remove.ok) throw new Error(remove.message); expect(remove.value.participants.map((item) => item.kind)).toEqual(["plugin-installation-delete", "plugin-installation-replace", "executable-admission-generation"]); expect((await removing.execute(remove.value, remove.value.confirmationDigest)).ok).toBe(true); state.snapshot = { ...reload(value), catalogSelections: selections(value, ids) }; expect(state.snapshot.rows.map((row) => row.pluginId)).toEqual(["other@official"]); expect(state.snapshot.rows[0]!.authority!.record.executableGenerationId).toBe(state.snapshot.completeReference!.generation.generationId);
  }, 30_000);

  it("rebinds a retained survivor across distinct admitted catalog snapshots", async () => {
    const value = await fixture(); const refreshed = await refreshedSnapshot(value, "next"); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value, ["other@official"]) } as PluginLocalSnapshot }; const first = build(value, state, "plugin_cross_snapshot_first").service; const installed = await first.install({ pluginId: "other@official", source: value.source, catalog: value.catalog }); if (!installed.ok) throw new Error(installed.message); expect((await first.execute(installed.value, installed.value.confirmationDigest)).ok).toBe(true); const snapshots = [value.snapshot, refreshed] as const; state.snapshot = { ...reload(value, snapshots), marketplaceRegistrations: [{ ...value.registration, selectedSnapshotId: refreshed.snapshotId }], marketplaceSnapshots: snapshots, catalogSelections: [{ pluginId: "other@official", registration: value.registration, snapshotId: value.catalog.snapshotId, catalogDigest: value.catalog.catalogDigest, source: value.source }, { pluginId: "tool@official", registration: { ...value.registration, selectedSnapshotId: refreshed.snapshotId }, snapshotId: refreshed.snapshotId, catalogDigest: refreshed.catalogDigest, source: value.source }] }; const second = build(value, state, "plugin_cross_snapshot_second").service; const preview = await second.install({ pluginId: "tool@official", source: value.source, catalog: { marketplaceName: "official", registration: { ...value.registration, selectedSnapshotId: refreshed.snapshotId }, snapshotId: refreshed.snapshotId, catalogDigest: refreshed.catalogDigest, snapshot: refreshed } }); if (!preview.ok) throw new Error(preview.message); expect((await second.execute(preview.value, preview.value.confirmationDigest)).ok).toBe(true); const loaded = reload(value, snapshots); expect(loaded.rows.map((row) => row.pluginId).sort()).toEqual(["other@official", "tool@official"]); expect(new Set(loaded.completeReference!.installations.map((item) => item.record.source.catalogDigest))).toEqual(new Set([value.catalog.catalogDigest, refreshed.catalogDigest]));
  });

  it("commits and fresh-loads a two-plugin survivor after data-bearing uninstall", async () => {
    const value = await fixture(); const ids = ["other@official", "tool@official"] as const; const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value, ids) } as PluginLocalSnapshot }; const currentCatalog = () => ({ ...value.catalog, snapshot: state.snapshot.marketplaceSnapshots[0]! });
    for (const [pluginId, id] of [["other@official", "plugin_data_other"], ["tool@official", "plugin_data_tool"]] as const) { const service = build(value, state, id).service; const preview = await service.install({ pluginId, source: value.source, catalog: currentCatalog() }); if (!preview.ok) throw new Error(preview.message); expect((await service.execute(preview.value, preview.value.confirmationDigest)).ok).toBe(true); state.snapshot = { ...reload(value), catalogSelections: selections(value, ids) }; }
    const dataPath = path.join(value.store.dataRoot, `plugin-${createHash("sha256").update("tool@official").digest("base64url")}`); fs.mkdirSync(dataPath); fs.writeFileSync(path.join(dataPath, "state.bin"), "retire"); const service = build(value, state, "plugin_data_remove").service; const selected = state.snapshot.rows.find((row) => row.pluginId === "tool@official")!.authority!; const preview = await service.uninstall("tool@official", { record: selected, removeData: true }); if (!preview.ok) throw new Error(preview.message); expect(preview.value.participants.map((item) => item.kind)).toEqual(["plugin-installation-delete", "plugin-installation-replace", "owned-data-retirement", "executable-admission-generation"]); expect((await service.execute(preview.value, preview.value.confirmationDigest)).ok).toBe(true); state.snapshot = { ...reload(value), catalogSelections: selections(value, ids) }; expect(state.snapshot.rows.map((row) => row.pluginId)).toEqual(["other@official"]); expect(fs.existsSync(dataPath)).toBe(false);
  }, 30_000);

  it("treats malformed persisted producer evidence as invalid instead of throwing", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; let interrupted = false; const service = build(value, state, "plugin_malformed_evidence", { hit: (phase, index) => { if (!interrupted && phase === "after-replacement" && index === 0) { interrupted = true; throw new Error("interrupt"); } } }).service; const preview = await service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!preview.ok) throw new Error(preview.message); expect((await service.execute(preview.value, preview.value.confirmationDigest)).ok).toBe(false); const journal = await readTransactionJournal(value.store, preview.value.operationId); if (!journal.ok) throw new Error(journal.message); const registry = pluginLifecycleTransactionRegistry(value.store, [value.snapshot]); if (!registry.ok) throw new Error(registry.message); const codec = registry.value.lookup("plugin-lifecycle", 1)!;
    for (const malformed of [null, [], {}, { role: "survivor-generation-rebind", predecessorEnvelopeBase64: 7, successorEnvelopeBase64: "%%%" }]) { const participants = journal.value.participants.map((participant, index) => index === 0 ? { ...participant, producerEvidence: malformed } : participant); expect(() => codec.validatePlan(participants)).not.toThrow(); expect(codec.validatePlan(participants)).toMatchObject({ ok: false }); }
    await service.recover(preview.value.operationId, "rollback");
  });

  it("derives the canonical union of survivor, active-checkout, and settings locks in both lexical orderings", async () => {
    const neighbor = (key: string, direction: "lower" | "higher"): `checkout-${string}` => { const alphabet = "-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz"; const suffix = key.slice("checkout-".length).split(""); for (let index = 0; index < suffix.length; index++) { const position = alphabet.indexOf(suffix[index]!); if (direction === "lower" && position > 0) { suffix[index] = alphabet[position - 1]!; return `checkout-${suffix.join("")}`; } if (direction === "higher" && position < alphabet.length - 1) { suffix[index] = alphabet[position + 1]!; return `checkout-${suffix.join("")}`; } } throw new Error(`Cannot derive ${direction} checkout witness`); };
    for (const direction of ["lower", "higher"] as const) {
      const value = await fixture(); if (value.checkoutFamilyKey === undefined) throw new Error("Fixture checkout key is absent"); const ids = ["other@official", "tool@official"] as const; const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value, ids) } as PluginLocalSnapshot }; const survivorService = build(value, state, `plugin_lock_survivor_${direction}`).service; const survivor = await survivorService.install({ pluginId: "other@official", source: value.source, catalog: value.catalog }, { scope: "project" }); if (!survivor.ok) throw new Error(survivor.message); expect((await survivorService.execute(survivor.value, survivor.value.confirmationDigest)).ok).toBe(true); state.snapshot = { ...reload(value), catalogSelections: selections(value, ids) };
      const selectedCheckout = neighbor(value.checkoutFamilyKey, direction); const service = build(value, state, `plugin_lock_selected_${direction}`, undefined, {}, selectedCheckout).service; const preview = await service.install({ pluginId: "tool@official", source: value.source, catalog: { ...value.catalog, snapshot: state.snapshot.marketplaceSnapshots[0]! } }, { scope: "project" }); expect(preview).toMatchObject({ ok: true }); if (!preview.ok) throw new Error(preview.message); expect((await service.execute(preview.value, preview.value.confirmationDigest)).ok).toBe(true); const receipt = await readTransactionReceipt(value.store, preview.value.operationId); if (!receipt.ok || receipt.value === undefined) throw new Error("Missing lock receipt"); const checkouts = [value.checkoutFamilyKey, selectedCheckout].sort((left, right) => Buffer.compare(Buffer.from(left), Buffer.from(right))); const settingsKey = createHash("sha256").update(preview.value.settingsEffect!.targetPath, "utf8").digest("base64url"); expect(receipt.value.requiredLocks).toEqual([{ kind: "profile", key: value.store.profileKey }, ...checkouts.map((key) => ({ kind: "checkout" as const, key })), { kind: "settings", key: settingsKey }]);
    }
  }, 30_000);

  it("rejects a bounded table of well-shaped contradictory persisted lifecycle relationships", async () => {
    const value = await fixture(); const ids = ["other@official", "tool@official"] as const; const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value, ids) } as PluginLocalSnapshot }; const first = build(value, state, "plugin_relationship_first").service; const installed = await first.install({ pluginId: "other@official", source: value.source, catalog: value.catalog }, { scope: "project" }); if (!installed.ok) throw new Error(installed.message); expect((await first.execute(installed.value, installed.value.confirmationDigest)).ok).toBe(true); state.snapshot = { ...reload(value), catalogSelections: selections(value, ids) }; let interrupted = false; const second = build(value, state, "plugin_relationship_pending", { hit: (phase, index) => { if (!interrupted && phase === "after-replacement" && index === 0) { interrupted = true; throw new Error("interrupt"); } } }).service; const projectSelector = second.list().find((row) => row.pluginId === "other@official")!.selector; expect(second.details(projectSelector)).toMatchObject({ ok: true, value: { pluginId: "other@official", scope: "project" } }); const preview = await second.install({ pluginId: "tool@official", source: value.source, catalog: { ...value.catalog, snapshot: state.snapshot.marketplaceSnapshots[0]! } }); if (!preview.ok) throw new Error(preview.message); expect(await second.execute(preview.value, preview.value.confirmationDigest)).toMatchObject({ ok: false, code: "pending-recovery" }); const journal = await readTransactionJournal(value.store, preview.value.operationId); if (!journal.ok) throw new Error(journal.message); const registry = pluginLifecycleTransactionRegistry(value.store, [value.snapshot]); if (!registry.ok) throw new Error(registry.message); const codec = registry.value.lookup("plugin-lifecycle", 1)!; const cloneParticipants = () => structuredClone(journal.value.participants) as unknown as Array<Record<string, unknown>>; const resign = (summary: Record<string, unknown>) => { const { confirmationDigest: _ignored, ...unsigned } = summary; const bytes = canonicalJsonBytes(unsigned); if (!bytes.ok) throw new Error(bytes.message); return { ...unsigned, confirmationDigest: digest(bytes.value) }; };
    const generationBytes = cloneParticipants(); generationBytes.at(-1)!["stagedDigest"] = digest(Buffer.from("contradictory-generation")); const generationTarget = cloneParticipants(); generationTarget.at(-1)!["targetPath"] = `${generationTarget.at(-1)!["targetPath"] as string}.other`; const predecessorBijection = cloneParticipants(); const predecessorEvidence = predecessorBijection.at(-1)!["producerEvidence"] as { predecessor: { installations: unknown[] } }; predecessorEvidence.predecessor.installations = [...predecessorEvidence.predecessor.installations, structuredClone(predecessorEvidence.predecessor.installations[0])]; const selectedAuthority = cloneParticipants(); const selectedRecord = (selectedAuthority[0]!["producerEvidence"] as { record: Record<string, unknown> }).record; selectedRecord["profileKey"] = "profile-contradictory"; const sourceTrust = cloneParticipants(); const sourceRecord = (sourceTrust[0]!["producerEvidence"] as { record: { source: Record<string, unknown>; trust: Record<string, unknown> } }).record; sourceRecord.source["url"] = "https://different.example.org/tool.zip"; sourceRecord.trust["target"] = "other@official"; const destructiveSummary = resign({ ...(structuredClone(journal.value.confirmationSummary) as Record<string, unknown>), action: "uninstall", removeData: true, removeDeclaration: true, consequences: ["Removes only the selected PiCC-owned installation and rebinds every survivor", "Removes the selected authentic enablement declaration", "Logically retires exact last-reference PiCC-owned data; physical cleanup is conservative best effort, not secure erasure", "Retires code only when no owned installation references it", "The running session remains unchanged until reload"] }); const lockSummary = resign({ ...(structuredClone(journal.value.confirmationSummary) as Record<string, unknown>), checkoutFamilyKey: "checkout-contradictory" });
    const selectedGraphSummary = (mutate: (row: Record<string, unknown>, graph: Array<Record<string, unknown>>) => void) => { const summary = structuredClone(journal.value.confirmationSummary) as unknown as Record<string, unknown>; const dependency = summary["dependencies"] as { graph: Array<Record<string, unknown>> }; const selectedRows = dependency.graph.filter((row) => row["pluginId"] === preview.value.pluginId); if (selectedRows.length !== 1) throw new Error("Expected one selected dependency graph row in valid persisted summary"); mutate(selectedRows[0]!, dependency.graph); summary["dependencies"] = pluginDependencyPosture(preview.value.pluginId, dependency.graph as never); return resign(summary); };
    const graphSummaries = [
      ["selected graph plugin identity", selectedGraphSummary((row) => { row["pluginId"] = "mutated@official"; })],
      ["selected graph version", selectedGraphSummary((row) => { row["version"] = "9.9.9"; })],
      ["selected graph ownership", selectedGraphSummary((row) => { row["ownership"] = "claude-imported-readonly"; })],
      ["selected graph enabled posture", selectedGraphSummary((row) => { row["enabled"] = false; })],
      ["selected graph availability", selectedGraphSummary((row) => { row["available"] = false; })],
      ["selected graph dependencies", selectedGraphSummary((row) => { row["dependencies"] = [{ name: "missing", itemIndex: 0 }]; })],
      ["selected graph declaration", selectedGraphSummary((row) => { row["dependencyDeclaration"] = "invalid"; })],
      ["selected graph allowlist", selectedGraphSummary((row) => { row["allowedCrossMarketplaceDependencies"] = ["mutated"]; })],
      ["duplicate selected graph row", selectedGraphSummary((row, graph) => { graph.push(structuredClone(row)); })],
    ] as const;
    for (const [name, participants, summary] of [["generation bytes", generationBytes, journal.value.confirmationSummary], ["generation target", generationTarget, journal.value.confirmationSummary], ["predecessor bijection", predecessorBijection, journal.value.confirmationSummary], ["selected authority", selectedAuthority, journal.value.confirmationSummary], ["source/trust", sourceTrust, journal.value.confirmationSummary], ["destructive order/flags", journal.value.participants, destructiveSummary], ["locks/summary", journal.value.participants, lockSummary], ...graphSummaries.map(([name, summary]) => [name, journal.value.participants, summary] as const)] as const) { const result = codec.requiredLocks(summary, participants as never); expect(result, name).toMatchObject({ ok: false }); }
    expect(journal.value.requiredLocks).toEqual([{ kind: "profile", key: value.store.profileKey }, { kind: "checkout", key: value.checkoutFamilyKey }, expect.objectContaining({ kind: "settings" })]); expect(codec.requiredLocks(journal.value.confirmationSummary, journal.value.participants)).toEqual({ ok: true, value: journal.value.requiredLocks }); await expect(second.recover(preview.value.operationId, "rollback")).resolves.toMatchObject({ ok: true, value: { outcome: "rolled-back" } });
  }, 30_000);

  it("returns failed terminal execution as non-success while lookup and direct receipt retain exact truth", async () => {
    const value = await fixture(); const state = { snapshot: { rows: [], marketplaceSnapshots: [value.snapshot], catalogSelections: selections(value) } as PluginLocalSnapshot }; const service = build(value, state, "plugin_failed_terminal", { hit: (phase) => { if (phase === "before-journal") throw new Error("fail before commit"); } }).service; const preview = await service.install({ pluginId: "tool@official", source: value.source, catalog: value.catalog }); if (!preview.ok) throw new Error(preview.message); const result = await service.execute(preview.value, preview.value.confirmationDigest); expect(result).toMatchObject({ ok: false, code: "failed-before-commit", receipt: { outcome: "failed-before-commit", summary: preview.value } }); expect(await service.receipt(preview.value.operationId)).toMatchObject({ ok: true, value: { outcome: "failed-before-commit" } }); expect(await service.lookupOperation(preview.value.operationId)).toMatchObject({ ok: true, value: { state: "terminal", receipt: { outcome: "failed-before-commit" } } });
  });

  it("composes the final trusted producer/transaction registries and rejects unknown codecs", async () => {
    const value = await fixture(); const trusted = createTrustedLifecycleRegistry(value.store, [value.snapshot]); expect(trusted.ok).toBe(true); if (!trusted.ok) return;
    expect(trusted.value.producers.lookup("marketplace-registration", 1)).toBeDefined(); expect(trusted.value.producers.lookup("marketplace-catalog-snapshot", 1)).toBeDefined(); expect(trusted.value.producers.lookup("plugin-installation", 1)).toBeDefined(); expect(trusted.value.producers.lookup("executable-admission-generation", 1)).toBeDefined(); expect(trusted.value.producers.lookup("project-selected", 1)).toBeUndefined();
    expect(trusted.value.transactions.lookup("plugin-settings", 1)).toBeDefined(); expect(trusted.value.transactions.lookup("marketplace-lifecycle", 1)).toBeDefined(); expect(trusted.value.transactions.lookup("plugin-lifecycle", 1)).toBeDefined(); expect(trusted.value.transactions.lookup("project-selected", 1)).toBeUndefined();
    expect(pluginLifecycleTransactionRegistry(value.store, [value.snapshot]).ok).toBe(true); expect(createPluginSettingsTransactionCodec().schema).toBe("plugin-settings");
  });
});
